/* Portal RYM V172 clean - Panapass reportes */
async function reportes(v){
  if(!state.modules.includes('reportes')){v.innerHTML='<div class="alert">Sin permiso para Reportes.</div>';return}
  const hoy=state.today||new Date().toISOString().slice(0,10), ini=hoy.slice(0,8)+'01';
  let est=[];try{est=await rpc('panapass_reportes_estado')}catch(_){}
  const last=t=>{const x=est.find(z=>z.tipo===t);return x?.ultimo_envio?`Último envío: ${fmtDT(x.ultimo_envio)}${x.desde?' · '+x.desde+' → '+x.hasta:''}`:'Sin envíos registrados todavía'};
  v.innerHTML=`<div class="source-card"><span class="entity-chip">CENTRO DE REPORTES</span><div class="source-text"><strong>Consulta, vista previa y control de envíos</strong><p>Los reportes digitales se preparan primero en pantalla. El historial registra el último rango enviado para evitar duplicados.</p></div></div>
  <div class="section-tools"><div class="field"><label>Desde</label><input id="repDesde" type="date" value="${ini}"></div><div class="field"><label>Hasta</label><input id="repHasta" type="date" value="${hoy}"></div></div>
  <div class="report-grid">
   <div class="report-card"><h3>Negativos AM por Galera</h3><p>Snapshot AM para compartir por galera y supervisora.</p><div class="report-actions"><button class="soft-btn" data-go="negativos_hoy">Ver negativos</button></div><div class="report-status">${last('NEGATIVOS_GALERA')}</div></div>
   <div class="report-card"><h3>Pagos del día por Galera</h3><p>Resultado real pagado en el día para cada galera.</p><div class="report-actions"><button class="soft-btn" data-go="historial">Ver pagos</button></div><div class="report-status">${last('PAGOS_GALERA')}</div></div>
   <div class="report-card"><h3>Pagos · 4 Galeras</h3><p>Consolidado por rango para revisar y compartir el desempeño de VCARS, VCOMP, VIPCO y VINDU.</p><div class="report-actions"><button class="soft-btn" data-go="historial">Consultar</button></div><div class="report-status">${last('PAGOS_4_GALERAS')}</div></div>
   <div class="report-card"><h3>Fondeo Administración</h3><p>Empresa + monto realmente pagado. Usa A PAGAR; nunca Con_boleta.</p><div class="report-actions"><button id="repFondeo">Vista previa</button></div><div class="report-status">${last('RESUMEN_FONDEO')}</div></div>
   <div class="report-card"><h3>No PRE Diario / Cobra</h3><p>Todo lo que no es PRE DIARIO para gestionar la carga por la ruta especial de Cobra.</p><div class="report-actions"><button id="repNoPre">Vista previa</button></div></div>
   <div class="report-card"><h3>Bajas Panapass</h3><p>Unidades no activas en Control de Auto que todavía aparecen en el último corte ENA.</p><div class="report-actions"><button id="repBajas">Consultar bajas</button></div></div>
  </div><div id="repOut" style="margin-top:14px"></div>`;
  document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.active=b.dataset.go;shell();render()});
  const out=document.querySelector('#repOut'),range=()=>({p_desde:document.querySelector('#repDesde').value,p_hasta:document.querySelector('#repHasta').value});
  document.querySelector('#repFondeo').onclick=async()=>{out.innerHTML='<div class="card">Calculando fondeo...</div>';try{const rows=await rpc('panapass_reporte_fondeo',range());const total=rows.reduce((a,x)=>a+Number(x.monto||0),0);out.innerHTML=`<div class="kpis"><div class="kpi"><span>Empresas</span><strong>${rows.length}</strong></div><div class="kpi"><span>Total pagado</span><strong>${money(total)}</strong></div></div>${tableHtml(rows,['empresa','monto','registros'],'pretty','mobile-cards')}`}catch(x){out.innerHTML=`<div class="alert">${esc(x.message)}</div>`}};
  document.querySelector('#repNoPre').onclick=async()=>{out.innerHTML='<div class="card">Consultando...</div>';try{const rows=await rpc('panapass_reporte_no_pre_diario',range());out.innerHTML=`<div class="kpis"><div class="kpi"><span>Registros</span><strong>${rows.length}</strong></div><div class="kpi"><span>Total A pagar</span><strong>${money(rows.reduce((a,x)=>a+Number(x.a_pagar||0),0))}</strong></div></div>${tableHtml(rows,['fecha','galera','empresa','unidad','placa','panapass_numero','a_pagar','numero_operador','nombre_operador','cobrador','tipo','estado_cobra'],'pretty compact-table','mobile-cards')}`}catch(x){out.innerHTML=`<div class="alert">${esc(x.message)}</div>`}};
  document.querySelector('#repBajas').onclick=async()=>{out.innerHTML='<div class="card">Cruzando Control de Auto vs ENA...</div>';try{const rows=await rpc('panapass_reporte_bajas_v2');out.innerHTML=`<div class="kpis"><div class="kpi"><span>Bajas pendientes</span><strong>${rows.length}</strong></div></div>${tableHtml(rows,['galera','administrador','empresa','unidad','placa','panapass_numero','estatus_control','ultima_lectura','saldo','cantidad_tags','tags_ena','accion'],'pretty compact-table','mobile-cards')}`}catch(x){out.innerHTML=`<div class="alert">${esc(x.message)}</div>`}};
}
