(function(){
  const role94=()=>String((typeof state!=='undefined'&&state?.profile?.rol)||'').trim().toUpperCase();
  const can94=()=>role94()==='ADMIN_TOTAL'||(typeof window.rymHasModule==='function'&&window.rymHasModule('control_auto.cupos_attt'));
  const E94=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const N94=v=>String(v??'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
  const fmt94=v=>{if(!v)return '—';try{return new Date(v).toLocaleString('es-PA',{timeZone:'America/Panama',dateStyle:'short',timeStyle:'short'})}catch(_){return String(v)}};
  function reconLabel94(x){const m={ECARCHECK_CONFIRMADO:'Confirmado eCarCheck',PENDIENTE_ECARCHECK:'Pendiente eCarCheck',ECARCHECK_DIFIERE:'eCarCheck difiere',STOCK_PERO_ECARCHECK_ASIGNADO:'Stock pero asignado ATTT',ASIGNADO_SIN_UNIDAD_ACTIVA:'Asignado sin unidad',REQUIERE_REVISION:'Requiere revisión',EN_TRAMITE:'En trámite',RETENIDO:'Retenido',STOCK:'Stock',BAJA:'Baja',REVISAR:'Revisar'};return m[x]||x||'—'}
  function reconClass94(x){return x==='ECARCHECK_CONFIRMADO'?'ok':x==='STOCK'?'stock':['PENDIENTE_ECARCHECK','EN_TRAMITE','RETENIDO'].includes(x)?'wait':'bad'}
  function src94(r){const a=[];if(r.fuente_control)a.push('<span class="v94-src">Control</span>');if(r.fuente_attt)a.push('<span class="v94-src attt">ATTT ref.</span>');if(r.fuente_pagador)a.push('<span class="v94-src pag">Pagador Excel</span>');if(r.fuente_ecarcheck)a.push('<span class="v94-src ecar">eCarCheck</span>');return a.join('')||`<span class="v94-src">${E94(r.fuente_principal||'Sin fuente')}</span>`}
  function ensureNav94(active){
    if(!document.body.classList.contains('v70-control')||!can94())return;
    const nav=document.querySelector('.side .nav');if(!nav)return;
    let b=nav.querySelector('[data-v94-control="cupos"]');
    if(!b){b=document.createElement('button');b.type='button';b.dataset.v94Control='cupos';b.textContent='Cupos ATTT';const units=nav.querySelector('[data-v75-control="unidades"]');if(units?.nextSibling)nav.insertBefore(b,units.nextSibling);else nav.appendChild(b);b.onclick=()=>window.v94ControlCuposATTT?.()}
    if(active==='cupos')nav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));
  }
  window.v94ControlCuposATTT=async function(){
    if(!can94())return;
    window.__v75ControlMode=true;document.body.classList.remove('v70-portal','v70-admin');document.body.classList.add('v70-control');
    ensureNav94('cupos');
    const top=document.querySelector('.top h1');if(top)top.textContent='Cupos ATTT';const kick=document.querySelector('.portal-kicker');if(kick)kick.textContent='Portal RYM · Control de Auto';
    const v=document.querySelector('#view');if(!v)return;v.innerHTML='<div class="card">Construyendo base maestra de Cupos ATTT...</div>';
    try{
      const rows=await rpc('control_auto_cupos_attt_v1',{p_buscar:null,p_estado:null,p_tipo:null,p_conciliacion:null,p_limit:5000});
      const states=[...new Set(rows.map(r=>r.estado).filter(Boolean))].sort(),types=[...new Set(rows.map(r=>r.tipo_cupo).filter(Boolean))].sort(),recons=[...new Set(rows.map(r=>r.conciliacion).filter(Boolean))].sort();
      v.innerHTML=`<div class="v94-cupos"><section class="v94-cupos-hero"><div><h2>Cupos ATTT</h2><p>Base maestra de inventario y asignación. <b>eCarCheck es la autoridad para la asignación actual</b>; Control de Auto/Sheets y las referencias ATTT o del pagador se conservan para conciliación y trazabilidad.</p></div><span class="v94-master-badge">Fuente maestra actual · eCarCheck</span></section><div id="v94Kpis"></div><section class="v94-cupos-source" id="v94Sources"></section><section class="v94-cupos-tools"><div class="v94-wide"><label>Buscar</label><input id="v94Q" placeholder="Cupo, unidad, placa, empresa o propietario"></div><div><label>Estado</label><select id="v94Estado"><option value="">Todos</option>${states.map(x=>`<option>${E94(x)}</option>`).join('')}</select></div><div><label>Tipo</label><select id="v94Tipo"><option value="">Todos</option>${types.map(x=>`<option>${E94(x)}</option>`).join('')}</select></div><div><label>Conciliación</label><select id="v94Recon"><option value="">Todas</option>${recons.map(x=>`<option value="${E94(x)}">${E94(reconLabel94(x))}</option>`).join('')}</select></div><div><label>Fuente</label><select id="v94Fuente"><option value="">Todas</option><option value="ECARCHECK">eCarCheck</option><option value="CONTROL">Control / Sheets</option><option value="ATTT">ATTT referencia</option><option value="PAGADOR">Pagador Excel</option></select></div></section><div class="v94-cupos-note"><b>Regla de seguridad:</b> una discrepancia de una unidad cerrada/traspasada no adjudica automáticamente al grupo el cupo del nuevo titular. Los cambios oficiales siguen pasando por la lógica de auditoría de Control de Auto.</div><div id="v94Count" class="v94-cupos-count"></div><section id="v94Out" class="v94-cupos-table"></section></div>`;
      const k=v.querySelector('#v94Kpis'),sources=v.querySelector('#v94Sources'),out=v.querySelector('#v94Out'),count=v.querySelector('#v94Count');
      const total=rows.length,asig=rows.filter(r=>r.estado==='ASIGNADO').length,conf=rows.filter(r=>r.conciliacion==='ECARCHECK_CONFIRMADO').length,stock=rows.filter(r=>r.estado==='STOCK').length,ret=rows.filter(r=>r.estado==='RETENIDO').length,review=rows.filter(r=>r.requiere_revision).length;
      k.innerHTML=`<div class="v94-cupos-kpis"><article class="v94-cupo-kpi"><span>Inventario total</span><strong>${total}</strong></article><article class="v94-cupo-kpi"><span>Asignados</span><strong>${asig}</strong></article><article class="v94-cupo-kpi good"><span>Confirmados eCarCheck</span><strong>${conf}</strong></article><article class="v94-cupo-kpi"><span>Stock</span><strong>${stock}</strong></article><article class="v94-cupo-kpi warn"><span>Retenidos</span><strong>${ret}</strong></article><article class="v94-cupo-kpi ${review?'bad':''}"><span>Requieren revisión</span><strong>${review}</strong></article></div>`;
      const cControl=rows.filter(r=>r.fuente_control).length,cAt=rows.filter(r=>r.fuente_attt).length,cPag=rows.filter(r=>r.fuente_pagador).length,cEc=rows.filter(r=>r.fuente_ecarcheck).length;
      sources.innerHTML=`<article class="v94-source-card"><span>Control de Auto / Sheets</span><b>${cControl}</b><small>Base migrada y dato operativo local.</small></article><article class="v94-source-card"><span>Referencia ATTT</span><b>${cAt}</b><small>Referencias externas ya incorporadas.</small></article><article class="v94-source-card"><span>Excel del pagador</span><b>${cPag}</b><small>${cPag?'Fuente importada y trazable.':'Pendiente cargar el archivo fuente.'}</small></article><article class="v94-source-card"><span>eCarCheck oficial</span><b>${cEc}</b><small>Autoridad para confirmar la asignación actual.</small></article>`;
      const q=v.querySelector('#v94Q'),es=v.querySelector('#v94Estado'),ts=v.querySelector('#v94Tipo'),rs=v.querySelector('#v94Recon'),fs=v.querySelector('#v94Fuente');
      const paint=()=>{const qq=N94(q.value),ee=es.value,tt=ts.value,rr=rs.value,ff=fs.value;const a=rows.filter(r=>(!qq||N94([r.numero_cupo,r.unidad,r.placa,r.empresa,r.galera,r.propietario_ecarcheck].join(' ')).includes(qq))&&(!ee||r.estado===ee)&&(!tt||r.tipo_cupo===tt)&&(!rr||r.conciliacion===rr)&&(!ff||(ff==='ECARCHECK'&&r.fuente_ecarcheck)||(ff==='CONTROL'&&r.fuente_control)||(ff==='ATTT'&&r.fuente_attt)||(ff==='PAGADOR'&&r.fuente_pagador)));count.textContent=`${a.length} de ${rows.length} cupos visibles`;out.innerHTML=`<div class="table-wrap"><table class="pretty"><thead><tr><th>Cupo</th><th>Estado</th><th>Conciliación</th><th>Unidad</th><th>Placa</th><th>Empresa / Galera</th><th>Control Auto</th><th>eCarCheck</th><th>Fuentes</th><th>Última validación</th></tr></thead><tbody>${a.map(r=>`<tr><td data-label="Cupo"><span class="v94-cupo-num">${E94(r.numero_cupo)}</span><div class="v94-muted">${E94(r.tipo_cupo||'')}</div></td><td data-label="Estado"><span class="v94-status ${E94(r.estado)}">${E94(r.estado)}</span></td><td data-label="Conciliación"><span class="v94-recon ${reconClass94(r.conciliacion)}">${E94(reconLabel94(r.conciliacion))}</span></td><td data-label="Unidad"><b>${E94(r.unidad||'—')}</b><div class="v94-muted">${E94(r.unidad_estatus||'')}</div></td><td data-label="Placa">${E94(r.placa||'—')}</td><td data-label="Empresa / Galera">${E94(r.empresa||'—')}<div class="v94-muted">${E94(r.galera||'')}</div></td><td data-label="Control Auto">${E94(r.cupo_control||'—')}</td><td data-label="eCarCheck">${E94(r.cupo_ecarcheck||'—')}<div class="v94-muted">${E94(r.propietario_ecarcheck||'')}</div></td><td data-label="Fuentes">${src94(r)}</td><td data-label="Última validación">${E94(fmt94(r.ecarcheck_actualizado_at||r.ultima_fuente_at))}</td></tr>`).join('')||'<tr><td colspan="10"><div class="empty">Sin cupos para estos filtros.</div></td></tr>'}</tbody></table></div>`};
      [es,ts,rs,fs].forEach(x=>x.onchange=paint);q.oninput=paint;paint();ensureNav94('cupos');
    }catch(e){v.innerHTML=`<div class="alert">${E94(e.message||e)}</div>`;ensureNav94('cupos')}
  };
  document.addEventListener('click',()=>{if(document.body.classList.contains('v70-control'))setTimeout(()=>ensureNav94(),0)},true);
  setTimeout(()=>ensureNav94(),0);
})();
