import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.111.0";
const URL=Deno.env.get('SUPABASE_URL')||'',SR=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',ANON=Deno.env.get('SUPABASE_ANON_KEY')||'';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const R=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,'content-type':'application/json','cache-control':'private, max-age=15'}});
const S=(v:any)=>String(v??'').trim(),U=(v:any)=>S(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const G=(v:any)=>{const x=U(v);return ['VCARS','VIPCARS','V CARS'].includes(x)?'VCARS':['VCOMP','VIPCO','VINDU'].includes(x)?x:(x||'OTROS')};
const MN=(v:any)=>({ENERO:1,FEBRERO:2,MARZO:3,ABRIL:4,MAYO:5,JUNIO:6,JULIO:7,AGOSTO:8,SEPTIEMBRE:9,SETIEMBRE:9,OCTUBRE:10,NOVIEMBRE:11,DICIEMBRE:12} as any)[U(v)]||Number(v)||0;
const DK=(v:any)=>{const t=v?Date.parse(String(v)):NaN;return Number.isFinite(t)?t:0};
const noCupo=(v:any)=>!S(v)||['NO APLICA','N/A','NA','SIN CUPO'].includes(U(v));
const ownerNorm=(v:any)=>U(v).replace(/[^A-Z0-9]/g,'').replace(/SOCIEDADANONIMA/g,'').replace(/SAS?$/g,'');
async function paged(q:any){let a:any[]=[];for(let f=0;;f+=1000){const {data,error}=await q.range(f,f+999);if(error)throw error;a.push(...(data||[]));if(!data||data.length<1000)break}return a}
async function inChunks(sb:any,table:string,select:string,col:string,vals:any[]){const out:any[]=[];for(let i=0;i<vals.length;i+=300){const ch=vals.slice(i,i+300);if(!ch.length)continue;const {data,error}=await sb.from(table).select(select).in(col,ch);if(error)throw error;out.push(...(data||[]))}return out}
function nowPA(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Panama',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date()),o:any={};for(const x of p)if(x.type!=='literal')o[x.type]=x.value;return {year:+o.year,month:+o.month,day:+o.day,date:`${o.year}-${o.month}-${o.day}`,label:`${o.year}-${o.month}-${o.day} ${o.hour}:${o.minute}:${o.second}`}}
function monthsLate(y:number,m:number,n:any){if(!y||!m)return 0;return Math.max(0,(n.year*12+n.month)-(y*12+m))}
function priority(late:number){if(late>=4)return {prioridad:'CRITICA',rank:1};if(late>=2)return {prioridad:'URGENTE',rank:2};if(late>=1)return {prioridad:'ALTA',rank:3};return {prioridad:'ACTUAL',rank:4}}
async function permissions(sb:any,userId:string,role:string){
 const [{data:rp},{data:up}]=await Promise.all([sb.from('rol_modulo_permisos').select('modulo_codigo,puede_ver,puede_crear,puede_editar').eq('rol',role),sb.from('usuario_permisos').select('modulo_codigo,puede_ver,puede_crear,puede_editar').eq('user_id',userId)]);
 const m=new Map<string,any>();for(const x of rp||[])m.set(String(x.modulo_codigo),x);for(const x of up||[])m.set(String(x.modulo_codigo),{...(m.get(String(x.modulo_codigo))||{}),...x});return (k:string)=>m.get(k)||{};
}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return R({ok:false,error:'method_not_allowed'},405);try{
 const auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))return R({ok:false,error:'unauthorized'},401);
 const uc=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),{data:ud,error:ue}=await uc.auth.getUser();if(ue||!ud?.user)return R({ok:false,error:'unauthorized'},401);
 const sb=createClient(URL,SR,{auth:{persistSession:false,autoRefreshToken:false}}),{data:p}=await sb.from('perfiles_usuario').select('id,nombre,rol,activo,galeras_scope,supervisora_id').eq('id',ud.user.id).maybeSingle();if(!p?.activo)return R({ok:false,error:'perfil_inactivo'},403);
 const input=await req.json().catch(()=>({})),unit=S(input.unidad);if(!unit||unit.length>80)return R({ok:false,error:'unidad_requerida'},400);
 const role=U(p.rol),perm=await permissions(sb,p.id,role),project=perm('control_auto.validador_unidad_app');if(project.puede_ver===false||!project.puede_ver)return R({ok:false,error:'revisados_sin_acceso'},403);
 const canBoletas=false; // No Portal operation/history capabilities are granted.
 const {data:allowed,error:scopeError}=await uc.rpc('panapass_unidades_detalle',{p_buscar:unit,p_limit:25});if(scopeError)throw scopeError;
 if(!(allowed||[]).some((u:any)=>U(u.unidad)===U(unit)))return R({ok:false,error:'unidad_sin_acceso'},403);
 const [{data:sups,error:se},units]=await Promise.all([sb.from('supervisoras').select('id,galera,nombre,email,activo'),paged(sb.from('unidades').select('id,unidad,estatus,empresa_operadora,empresa_duena,placa_unica,placa_comercial,mes_revisado,supervisora_id,marca,modelo,anio,color').ilike('estatus','activo').eq('unidad',unit))]);if(se)throw se;
 const sm=new Map((sups||[]).map((x:any)=>[String(x.id),x])),scopes=(Array.isArray(p.galeras_scope)?p.galeras_scope:[]).map(G).filter(Boolean),global=role==='ADMIN_TOTAL'||role==='PAGADOR';
 const gal=(u:any)=>G(u.empresa_operadora||sm.get(String(u.supervisora_id||''))?.galera),visible=(u:any)=>global?true:role==='SUPERVISORA'?String(u.supervisora_id||'')===String(p.supervisora_id||''):scopes.includes(gal(u));
 const vu=units,ids=vu.map((x:any)=>x.id); // Exact unit already authorized by caller RPC.
 const latestRunQ=await sb.from('revisados_boletas_consulta').select('run_id,updated_at').not('run_id','is',null).order('updated_at',{ascending:false}).limit(1);if(latestRunQ.error)throw latestRunQ.error;const latestRun=latestRunQ.data?.[0]?.run_id||null;
 const [ops,official,logistics,companies,sync,boletas,incs,types,latestEcar]=await Promise.all([
   inChunks(sb,'revisados_operacion_estado','unidad_id,estado_revisado,anio_requerido,ultimo_anio_emitido,ultimo_revisado_id,fecha_ultimo_revisado,boleta_pendiente,fotos_disponibles,cantidad_fotos,actualizado_at','unidad_id',ids),
   inChunks(sb,'revisados_vehiculo_oficial','unidad_id,placa,cupo,propietario,documento_propietario,vin,chasis,motor,marca,modelo,anio,color,mes_revisado,anio_revisado,rev_id,fecha_revisado,tipo_placa,tipo_uso,estado_vehiculo,ultima_respuesta,actualizado_at','unidad_id',ids),
   inChunks(sb,'logistictodo_estados','unidad,status2,estatus_interno,activa,sincronizado_at','unidad',vu.map((x:any)=>x.unidad).filter(Boolean)),
   sb.from('empresas').select('id,nombre,galera,activo').then((x:any)=>{if(x.error)throw x.error;return x.data||[]}),
   sb.from('revisados_sync_estado').select('id,estado,iniciado_at,finalizado_at,ultimo_exito_at,ultimo_error,conteos,detalle,updated_at').eq('id','ecarcheck_live').limit(1).then((x:any)=>{if(x.error)throw x.error;return x.data||[]}),
   latestRun?sb.from('revisados_boletas_consulta').select('run_id,empresa_id,muestra,clasificacion_empresa,galera_raw,empresa_duena_raw,placa,boleta,unidad_id,source_payload,updated_at').eq('run_id',latestRun).then((x:any)=>{if(x.error)throw x.error;return x.data||[]}):Promise.resolve([]),
   inChunks(sb,'revisados_incidencias','unidad_id,bloquea_emision,estado','unidad_id',ids),
   Promise.resolve([]),
   inChunks(sb,'ecarcheck_v2_ultima_por_placa','placa_norm,placa,queue_id,tipo_consulta,origen,estado,ultima_consulta_at,error_code,error_detail,result_id,result_status,tipo_resultado,detalle,boletas,bloqueo,consultado_en,bridge_version','placa_norm',vu.map((x:any)=>U(x.placa_unica).replace(/\\s+/g,'')).filter(Boolean))
 ]);
 const om=new Map(ops.map((x:any)=>[String(x.unidad_id),x])),fm=new Map(official.map((x:any)=>[String(x.unidad_id),x])),lm=new Map(logistics.map((x:any)=>[U(x.unidad),x])),em=new Map(latestEcar.map((x:any)=>[U(x.placa_norm),x]));
 const now=nowPA(),validCompanies=companies.filter((x:any)=>x.activo!==false).map((x:any)=>({name:x.nombre,n:ownerNorm(x.nombre)})).filter((x:any)=>x.n.length>=4),ownerMatches=(owner:any,expected:any)=>{const a=ownerNorm(owner),b=ownerNorm(expected);if(!a||!b)return null;if(a.includes(b)||b.includes(a))return true;const known=validCompanies.find((x:any)=>a.includes(x.n)||x.n.includes(a));return known?ownerNorm(known.name)===b:false};
 const companyClass=new Map<string,string>(),plateBoleta=new Map<string,string>(),bm=new Map<string,any>();let latestRunAt=0;for(const b of boletas){latestRunAt=Math.max(latestRunAt,DK(b.updated_at));const key=G(b.galera_raw)+'|'+U(b.empresa_duena_raw);if(b.clasificacion_empresa)companyClass.set(key,U(b.clasificacion_empresa));if(b.placa)plateBoleta.set(U(b.placa),U(b.boleta));if(canBoletas){if(!bm.has(key))bm.set(key,{galera:G(b.galera_raw),empresa:b.empresa_duena_raw||'',clasificacion:U(b.clasificacion_empresa||'SIN DATOS'),checks:[]});bm.get(key).checks.push({muestra:Number(b.muestra||0),placa:b.placa||'',boleta:U(b.boleta||''),unidad:b.source_payload?.unidad||'',updated_at:b.updated_at})}}
 const incOpen=new Map<string,any[]>();for(const i of incs){if(i.estado==='ABIERTA'){const k=String(i.unidad_id);if(!incOpen.has(k))incOpen.set(k,[]);incOpen.get(k)!.push(i)}}
 const COLOR_AUDIT:any={I236:{anterior:'GRIS',nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},V561:{anterior:null,nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},V658:{anterior:'PLATEADO',nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},V952:{anterior:null,nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},P485:{anterior:'BLANCO',nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},P488:{anterior:'BEIGE',nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},P568:{anterior:'BLANCO',nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},P570:{anterior:'BLANCO',nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},C548:{anterior:null,nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},C551:{anterior:'PLATEADO',nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'},C634:{anterior:'TITAN GREY',nuevo:'AMARILLO',at:'2026-09-23T05:00:00Z'}};
 const rows:any[]=[];let covered=0,pending=0,noPhotos=0,withBoleta=0,withCompanyBoleta=0,critical=0,pendingColor=0,pendingExternal=0,pendingNormal=0;
 for(const u of vu){const o:any=om.get(String(u.id))||{},f:any=fm.get(String(u.id))||{},l:any=lm.get(U(u.unidad))||{},e:any=em.get(U(u.placa_unica).replace(/\\s+/g,''))||{},month=MN(u.mes_revisado),req=Number(o.anio_requerido||0),last=Number(o.ultimo_anio_emitido||0),baseCovered=month>0&&req>0&&last>=req,manualColor=COLOR_AUDIT[U(u.unidad)]||null,postAuditRym=!!manualColor&&DK(o.fecha_ultimo_revisado)>DK(manualColor.at),colorRehacer=!!manualColor&&!postAuditRym,actionableMonth=month>0&&month<=now.month,isCovered=baseCovered&&!colorRehacer,late=baseCovered?0:monthsLate(req,month,now),pri=colorRehacer?{prioridad:'ALTA',rank:0}:priority(late),g=gal(u),controlCupo=S(u.placa_comercial),officialCupo=S(f.cupo),controlColor=U(u.color),officialColor=U(f.color),officialWorkshop=U(f.ultima_respuesta?.ultTallerRevisado||''),externalWorkshop=actionableMonth&&!baseCovered&&String(f.ultima_respuesta?.anioRevisadoActual||'')===String(now.year)&&!!officialWorkshop&&!officialWorkshop.includes('986')&&!officialWorkshop.includes('REPUESTOS Y MULTISERVICIOS'),requiereAtencion=actionableMonth&&!isCovered,alerts:any[]=[];
   if(colorRehacer)alerts.push({tipo:'CAMBIO_COLOR_REHACER',nivel:'ALTA',texto:`Rehacer revisado por cambio de color${manualColor?.anterior?`: ${manualColor.anterior} → ${manualColor.nuevo||f.color||'actual'}`:''}`});
   if(f.actualizado_at&&officialColor&&controlColor&&officialColor!==controlColor)alerts.push({tipo:'COLOR',nivel:officialColor==='AMARILLO'?'ALTA':'MEDIA',texto:`Color ${u.color||'—'} → ${f.color||'—'}`});
   if(f.actualizado_at&&officialCupo&&U(officialCupo)!==U(controlCupo))alerts.push({tipo:'CUPO',nivel:'ALTA',texto:`Cupo ${controlCupo||'—'} → ${officialCupo}`});
   if(f.actualizado_at&&officialColor==='AMARILLO'&&noCupo(officialCupo||controlCupo))alerts.push({tipo:'SIN_CUPO',nivel:'ALTA',texto:'Amarillo sin cupo'});
   const own=ownerMatches(f.propietario,u.empresa_duena);if(f.actualizado_at&&own===false)alerts.push({tipo:'PROPIETARIO',nivel:'CRITICA',texto:'Propietario no coincide'});
   const eBoletas=e.boletas||{},ePlaca=Number(eBoletas?.boletasPorPlaca?.cantidad||0),eDoc=Number(eBoletas?.boletasPorDocumento?.cantidad||0),eEna=Number(eBoletas?.infraccionesEna?.cantidad||0),eDetail=S(e.detalle||e.error_detail),eState=U(e.estado),eTechnicalPending=U(e.error_code)==='ECARCHECK_JSON_PLACA'||/JSON VALUE COULD NOT BE CONVERTED|PATH:\s*\$\.PLACA|SYSTEM\.STRING/.test(U(eDetail)),eDisplayState=eTechnicalPending?'PENDIENTE':eState,eDisplayDetail=eTechnicalPending?'Pendiente de reconsulta eCarCheck. El intento anterior falló por un error técnico de formato de placa ya corregido.':eDetail,eCats:any[]=[];if(ePlaca>0)eCats.push({tipo:'BOLETA_PLACA',cantidad:ePlaca,alcance:'PLACA'});if(eDoc>0||eEna>0)eCats.push({tipo:'ENA_EMPRESA_DOCUMENTO',cantidad:Math.max(eDoc,eEna),boletas_documento:eDoc,infracciones_ena:eEna,alcance:'EMPRESA_DOCUMENTO'});if(/HURTO/.test(U(eDetail)))eCats.push({tipo:'RESTRICCION_PLACA_HURTO',cantidad:1,alcance:'PLACA'});if(/COLISION|COLISIÓN/.test(U(eDetail))&&/FUGA/.test(U(eDetail)))eCats.push({tipo:'RESTRICCION_PLACA_COLISION_FUGA',cantidad:1,alcance:'PLACA'});else if(/COLISION|COLISIÓN/.test(U(eDetail)))eCats.push({tipo:'RESTRICCION_PLACA_COLISION',cantidad:1,alcance:'PLACA'});else if(/FUGA/.test(U(eDetail)))eCats.push({tipo:'RESTRICCION_PLACA_FUGA',cantidad:1,alcance:'PLACA'});if(!eTechnicalPending&&eState==='ERROR')eCats.push({tipo:'ERROR_RESPUESTA',cantidad:1});
   const cKey=g+'|'+U(u.empresa_duena),boletaEmpresa=companyClass.get(cKey)==='BOLETA EMPRESA',boletaUnidad=!!o.boleta_pendiente||plateBoleta.get(U(u.placa_unica))==='SI';if(boletaEmpresa)alerts.push({tipo:'BOLETA_EMPRESA',nivel:'CRITICA',texto:'La empresa tiene boleta; no emitir hasta resolver.'});if(boletaUnidad&&!boletaEmpresa)alerts.push({tipo:'BOLETA_UNIDAD',nivel:'CRITICA',texto:'Boleta asociada a la unidad.'});
   if(requiereAtencion){pending++;if(colorRehacer)pendingColor++;else if(externalWorkshop)pendingExternal++;else pendingNormal++;}else if(month>0)covered++;if(!o.fotos_disponibles)noPhotos++;if(boletaUnidad)withBoleta++;if(boletaEmpresa)withCompanyBoleta++;if(requiereAtencion&&pri.prioridad==='CRITICA')critical++;
   const open=incOpen.get(String(u.id))||[],blockedManual=open.some((i:any)=>i.bloquea_emision!==false);
   rows.push({unidad:u.unidad||'',unidad_id:u.id,galera:g,empresa:u.empresa_duena||'',placa:u.placa_unica||'',cupo_control:controlCupo,cupo_ecarcheck:officialCupo,color_control:u.color||'',color_ecarcheck:f.color||'',mes:u.mes_revisado||'',mes_num:month,supervisora:sm.get(String(u.supervisora_id||''))?.nombre||'',supervisora_id:u.supervisora_id||null,ultimo_revisado:o.fecha_ultimo_revisado||f.fecha_revisado||f.ultima_respuesta?.fechaRevisado||null,ultimo_revisado_id:o.ultimo_revisado_id||f.rev_id||null,ultimo_revisado_fuente:o.fecha_ultimo_revisado?'EMISION':(f.fecha_revisado||f.ultima_respuesta?.fechaRevisado?'FICHA_ECARCHECK':null),ultimo_anio_emitido:last||null,anio_requerido:req||null,estado:!month?'SIN_MES':(requiereAtencion?'PENDIENTE':'VIGENTE'),emitido:isCovered,requiere_atencion:requiereAtencion,pendiente_tipo:requiereAtencion?(colorRehacer?'CAMBIO_COLOR':(externalWorkshop?'REVISADO_EXTERNO':'REVISADO_NORMAL')):null,meses_atraso:late,prioridad:requiereAtencion?pri.prioridad:'NORMAL',prioridad_rank:requiereAtencion?pri.rank:9,fotos_disponibles:!!o.fotos_disponibles,cantidad_fotos:Number(o.cantidad_fotos||0),boleta_pendiente:boletaUnidad,boleta_empresa:boletaEmpresa,bloqueado_auto:boletaEmpresa||boletaUnidad,bloqueado_manual:blockedManual,bloqueado:boletaEmpresa||boletaUnidad||blockedManual,incidencias_abiertas:open,status2:l.status2||'',estatus_logistica:l.estatus_interno||'',logistica_sync:l.sincronizado_at||null,propietario_ecarcheck:f.propietario||'',ficha_ecarcheck_at:f.actualizado_at||null,ecarcheck_estado:eDisplayState||null,ecarcheck_ultima_consulta_at:e.ultima_consulta_at||e.consultado_en||null,ecarcheck_detalle:eDisplayDetail||'',ecarcheck_boletas_placa:ePlaca,ecarcheck_boletas_documento:eDoc,ecarcheck_infracciones_ena:eEna,ecarcheck_categorias:eCats,ecarcheck_tipo_resultado:eTechnicalPending?'PENDIENTE_REINTENTO':(e.tipo_resultado||null),vin:f.vin||'',chasis:f.chasis||'',motor:f.motor||'',marca_control:u.marca||'',modelo_control:u.modelo||'',anio_control:u.anio||null,marca_ecarcheck:f.marca||'',modelo_ecarcheck:f.modelo||'',anio_ecarcheck:f.anio||null,tipo_uso:f.tipo_uso||'',estado_vehiculo:f.estado_vehiculo||'',alerts});}
 return R({ok:true,generated_at:new Date().toISOString(),rows:rows.map(({incidencias_abiertas,...row}:any)=>row)});
}catch(e){return R({ok:false,error:String((e as any)?.message||e)},500)}});
