/* Portal RYM V172 — isolated, source-specific validator services. */
(function(w){'use strict';
  const ev=()=>w.RYM_VALIDATOR_EVALUATOR;
  const norm=v=>ev().normal(v).replace(/[\s-]+/g,'');
  const req=(path,body)=>{if(typeof w.req!=='function')throw Error('Sesión no disponible');return w.req(path,{method:'POST',body:JSON.stringify(body)});};
  const rpc=(fn,body)=>{if(typeof w.rpc!=='function')throw Error('Servicio no disponible');return w.rpc(fn,body);};
  const match=(rows,seed)=>{const keys=[seed?.unidad,seed?.placa_unica,seed?.placa,seed?.placa_comercial,seed?.panapass_numero].map(norm).filter(Boolean);return (rows||[]).find(r=>keys.some(k=>[r.unidad,r.placa,r.placa_unica,r.placa_comercial,r.panapass_numero].map(norm).includes(k)))||null;};
  async function search(query){const q=String(query||'').trim();if(q.length<2)return [];let rows=await rpc('panapass_control_auto_v2',{p_grupo:null,p_buscar:q,p_limit:8}).catch(()=>[]);if(!Array.isArray(rows)||!rows.length)rows=await rpc('panapass_unidades_detalle',{p_buscar:q,p_limit:8}).catch(()=>[]);return Array.isArray(rows)?rows:[];}
  async function validatorControlAutoService(seed){const row=seed?.unidad?seed:(await search(seed))[0];if(!row)return ev().item('control','incompleta','Unidad no encontrada');const estado=String(row.estatus||row.estado||'').toUpperCase();if(ev().isControlBlocked(estado))return ev().item('control','bloqueada','Unidad cerrada o canibalizada',{estado,row});if(!['ACTIVO','CONVENIO'].includes(estado))return ev().item('control','alerta','La unidad no está activa',{estado,row});return ev().item('control','ok','Unidad activa',{estado,row});}
  async function validatorRevisadosService(control){try{const r=await req('/functions/v1/revisados-final',{});if(!r?.data?.ok)throw Error('Sin respuesta');const rev=match(r.data.rows,control.details?.row||control);if(!rev)return ev().item('revisado','incompleta','Sin registro de Revisado');const vigente=!!rev.emitido||String(rev.estado||'').toUpperCase()==='VIGENTE';return ev().item('revisado',vigente?(rev.bloqueado?'alerta':'ok'):'alerta',vigente?'Revisado vigente':'Revisado vencido o pendiente',{row:rev,estado:rev.estado||'—'});}catch(_){return ev().item('revisado','incompleta','Pendiente de conexión Revisados');}}
  async function validatorPanapassService(control){const row=control.details?.row||{},pan=String(row.panapass_numero||'').trim();if(!pan)return ev().item('panapass','incompleta','Pendiente de validación Panapass');try{const r=await req('/functions/v1/ena-consulta-saldo',{panapass:Number(pan)});const result=r?.data?.results?.[0];if(!r?.data?.ok||!result)throw Error('Sin respuesta');const saldo=Number(String(result?.summary?.saldo_texto||row.ena_saldo||'').replace(/[^\d.-]/g,''));if(!Number.isFinite(saldo))return ev().item('panapass','incompleta','Información Panapass no disponible',{panapass:pan});return ev().item('panapass',saldo<0?'alerta':'ok',saldo<0?'Saldo negativo':'Al día',{panapass:pan,saldo,consulta:result.ultima_consulta||null});}catch(_){return ev().item('panapass','incompleta','Pendiente de conexión Panapass',{panapass:pan});}}
  async function validatorGpsService(control){const unit=control.details?.row?.unidad||control.details?.unidad;if(!unit)return ev().item('gps','incompleta','Unidad no disponible para GPS');try{const r=await req('/functions/v1/gps-rym-validator',{q:String(unit)});if(!r?.data?.ok)throw Error('Sin respuesta');const row=match(r.data.rows,{unidad:unit});if(!row)return ev().item('gps','incompleta','Sin información GPS');const g1=row.gps1||{},g2=row.gps2||{},reports=!!g1.ok||!!g2.ok;if(!g1.installed&&!g2.installed)return ev().item('gps','alerta','Sin GPS instalado',{row});return ev().item('gps',reports?'ok':'alerta',reports?'GPS operativo':'GPS sin reporte',{row,gps1:g1,gps2:g2});}catch(_){return ev().item('gps','incompleta','Pendiente de conexión GPS');}}
  w.RYM_VALIDATOR_SERVICES=Object.freeze({normalize:norm,search,validatorControlAutoService,validatorRevisadosService,validatorPanapassService,validatorGpsService});
})(window);
