/* Portal RYM V172 clean - Control Auto Cupos filters */
(function(w){
 'use strict';
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const N=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
 const fmt=v=>{if(!v)return '—';try{return new Intl.DateTimeFormat('es-PA',{timeZone:'America/Panama',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(_){return String(v)}};
 /* ---------------- Cupos ATTT: KPI + filtros sobre dataset completo antes de paginar ---------------- */
 let cuposCache=null,cuposAt=0;
 async function cuposData(){if(cuposCache&&Date.now()-cuposAt<60000)return cuposCache;cuposCache=await rpc('control_auto_cupos_attt_v4',{p_limit:5000});cuposAt=Date.now();return cuposCache}
 const cupoLabels={OK_COINCIDE:'COINCIDE',PENDIENTE_VALIDAR_ECARCHECK:'PENDIENTE VALIDAR eCarCheck',CONTROL_TIENE_ECAR_SIN_CUPO:'CONTROL TIENE / ATTT NO',CONTROL_SIN_CUPO_ECAR_TIENE:'ATTT TIENE / CONTROL NO',CUPO_DIFERENTE:'CUPO DIFERENTE',AMARILLA_SIN_CUPO_OFICIAL:'AMARILLA SIN CUPO ATTT',FUERA_OPERACION_CON_CUPO:'FUERA OPERACIÓN CON CUPO DEL GRUPO',TRASPASO_TERCERO:'TRASPASO / CUPO DE TERCERO',NO_AMARILLA_CON_CUPO:'NO AMARILLA CON CUPO',NO_APLICA_NO_AMARILLA:'NO APLICA',FUERA_OPERACION_SIN_CUPO:'NO APLICA'};
 function cupoBadge(x){const z=N(x),c=(z==='OK_COINCIDE'||z==='TRASPASO_TERCERO')?'ok':z==='PENDIENTE_VALIDAR_ECARCHECK'?'warn':(z.includes('FUERA')||z.includes('DIFERENTE')||z.includes('SIN_CUPO')||z.includes('AMARILLA_SIN')||z.includes('NO_AMARILLA_CON'))?'bad':'warn';return '<span class="v147-badge '+c+'">'+E(cupoLabels[z]||x||'—')+'</span>'}
 function installCuposControl(d){
   const root=document.querySelector('.v94-cupos'),panel=document.querySelector('#v147Panel'),bc=document.querySelector('#v147Control'),ba=document.querySelector('#v147Asignador');if(!root||!panel||!bc||!ba)return;
   const rows=d?.rows||[];const bad=new Set(['CONTROL_TIENE_ECAR_SIN_CUPO','AMARILLA_SIN_CUPO_OFICIAL','CONTROL_SIN_CUPO_ECAR_TIENE','CUPO_DIFERENTE','FUERA_OPERACION_CON_CUPO','NO_AMARILLA_CON_CUPO']),actionable=new Set([...bad,'PENDIENTE_VALIDAR_ECARCHECK']);let mode='TODAS';
   const cards=[...root.querySelectorAll('.v147-kpis .v147-kpi')],modes=['ACTIVAS','AMARILLAS','CON_CUPO','SIN_CUPO','PENDIENTES','ALERTAS','FUERA'];cards.forEach((c,i)=>{c.classList.add('v154-click');c.dataset.v154Mode=modes[i]||'TODAS';c.title='Ver unidades de este indicador'});
   function setup(){
     const q=panel.querySelector('#v147CQ'),view=panel.querySelector('#v147CF'),count=panel.querySelector('#v147CC'),out=panel.querySelector('#v147CO'),pager=panel.querySelector('#v148CPager'),tools=q?.closest('.v94-cupos-tools');if(!q||!view||!count||!out||!pager||!tools)return;
     tools.classList.add('v154-cupos-tools');
     const add=(id,label,vals,render=x=>x)=>{let wrap=tools.querySelector('[data-v154="'+id+'"]');if(!wrap){wrap=document.createElement('div');wrap.dataset.v154=id;wrap.innerHTML='<label>'+label+'</label><select id="'+id+'"><option value="">Todos</option>'+vals.map(x=>'<option value="'+E(x)+'">'+E(render(x))+'</option>').join('')+'</select>';tools.appendChild(wrap)}return wrap.querySelector('select')};
     const gal=add('v154CuposGal','Galera',[...new Set(rows.map(r=>r.galera).filter(Boolean))].sort());
     const col=add('v154CuposColor','Color',[...new Set(rows.map(r=>r.color_control).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'es')));
     const est=add('v154CuposEst','Estatus',[...new Set(rows.map(r=>r.estatus).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'es')));
     const res=add('v154CuposRes','Resultado',[...new Set(rows.map(r=>r.comparacion).filter(Boolean))].sort(),x=>cupoLabels[N(x)]||x);
     let page=1;const pageSize=50;
     const matchMode=r=>mode==='TODAS'||(mode==='ACTIVAS'&&r.es_activa)||(mode==='AMARILLAS'&&r.es_activa&&r.es_amarilla)||(mode==='CON_CUPO'&&r.es_activa&&r.es_amarilla&&!!r.cupo_ecarcheck)||(mode==='SIN_CUPO'&&r.es_activa&&r.es_amarilla&&!r.cupo_ecarcheck&&r.comparacion!=='PENDIENTE_VALIDAR_ECARCHECK')||(mode==='PENDIENTES'&&r.comparacion==='PENDIENTE_VALIDAR_ECARCHECK')||(mode==='ALERTAS'&&actionable.has(r.comparacion))||(mode==='FUERA'&&['FUERA_OPERACION_CON_CUPO','TRASPASO_TERCERO'].includes(r.comparacion));
     const paint=()=>{const t=N(q.value),a=rows.filter(r=>(!t||N([r.unidad,r.placa_unica,r.empresa,r.galera,r.cupo_control,r.cupo_ecarcheck,r.propietario_ecarcheck,r.color_control,r.estatus].join(' ')).includes(t))&&(view.value==='TODAS'||(view.value==='AMARILLAS'&&r.es_activa&&r.es_amarilla)||(view.value==='PENDIENTES'&&r.comparacion==='PENDIENTE_VALIDAR_ECARCHECK')||(view.value==='ALERTAS'&&actionable.has(r.comparacion)))&&(!gal.value||String(r.galera||'')===gal.value)&&(!col.value||String(r.color_control||'')===col.value)&&(!est.value||String(r.estatus||'')===est.value)&&(!res.value||String(r.comparacion||'')===res.value)&&matchMode(r));const pages=Math.max(1,Math.ceil(a.length/pageSize));if(page>pages)page=pages;const slice=a.slice((page-1)*pageSize,page*pageSize),from=a.length?(page-1)*pageSize+1:0,to=Math.min(page*pageSize,a.length);count.textContent=a.length+' registros filtrados · '+rows.length+' unidades cargadas';out.innerHTML='<div class="table-wrap"><table class="pretty"><thead><tr><th>Unidad</th><th>Estatus</th><th>Color</th><th>Placa</th><th>Empresa</th><th>Cupo Control</th><th>Cupo eCarCheck</th><th>Titular ATTT</th><th>Última consulta exitosa</th><th>Resultado</th></tr></thead><tbody>'+ (slice.length?slice.map(r=>'<tr><td data-label="Unidad"><b>'+E(r.unidad)+'</b><div class="v96-mini">'+E(r.galera||'')+'</div></td><td data-label="Estatus">'+E(r.estatus||'—')+'</td><td data-label="Color">'+E(r.color_control||'—')+'</td><td data-label="Placa">'+E(r.placa_unica||'—')+'</td><td data-label="Empresa">'+E(r.empresa||'—')+'</td><td data-label="Cupo Control">'+E(r.cupo_control||'—')+'</td><td data-label="Cupo eCarCheck"><b>'+E(r.cupo_ecarcheck||'—')+'</b></td><td data-label="Titular ATTT">'+E(r.propietario_ecarcheck||'—')+'</td><td data-label="Última consulta">'+E(fmt(r.ultima_consulta_exitosa_at))+'</td><td data-label="Resultado">'+cupoBadge(r.comparacion)+'</td></tr>').join(''):'<tr><td colspan="10" class="empty">Sin resultados.</td></tr>')+'</tbody></table></div>';pager.innerHTML='<div class="v148-pager"><div class="v148-pager-left">'+from+'–'+to+' de '+a.length+' registros</div><div class="v148-pager-right"><button id="v154CPrev" '+(page<=1?'disabled':'')+'>← Anterior</button><span class="v148-page-label">Página '+page+' de '+pages+'</span><button id="v154CNext" '+(page>=pages?'disabled':'')+'>Siguiente →</button></div></div>';pager.querySelector('#v154CPrev')?.addEventListener('click',()=>{if(page>1){page--;paint()}});pager.querySelector('#v154CNext')?.addEventListener('click',()=>{if(page<pages){page++;paint()}})};
     q.oninput=()=>{page=1;paint()};[view,gal,col,est,res].forEach(x=>x.onchange=()=>{page=1;paint()});
     cards.forEach(c=>c.onclick=()=>{cards.forEach(x=>x.classList.remove('v154-selected'));c.classList.add('v154-selected');mode=c.dataset.v154Mode||'TODAS';if(mode==='AMARILLAS')view.value='AMARILLAS';else if(mode==='PENDIENTES')view.value='PENDIENTES';else if(mode==='ALERTAS')view.value='ALERTAS';else view.value='TODAS';page=1;paint();out.scrollIntoView({behavior:'smooth',block:'start'})});
     paint();
   }
   const oldControl=bc.onclick,oldAsign=ba.onclick;bc.onclick=()=>{oldControl?.();setTimeout(setup,0)};ba.onclick=()=>oldAsign?.();setup();
 }

 async function enhanceCupos(){try{installCuposControl(await cuposData())}catch(e){console.warn('V154 Cupos',e)}}
 if(!w.RYM_CONTROL_ROUTER?.after)throw new Error('Control router hook API unavailable');
 w.RYM_CONTROL_ROUTER.after('cupos',enhanceCupos);
})(window);
