/* Portal RYM V172 clean - Revisados dependent filters */
(function(w){
 'use strict';
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const N=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
 const fmt=v=>{if(!v)return '—';try{return new Intl.DateTimeFormat('es-PA',{timeZone:'America/Panama',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(_){return String(v)}};
 /* ---------------- Revisados: filtros dependientes activados solo al entrar/cambiar tab ---------------- */
 let revBusy=false;
 async function enhanceRev(){const bar=document.querySelector('.v66-filterbar');if(!bar||bar.dataset.v154Smart||revBusy)return;let cache=window.__v106RevisadosCache;if(!cache?.rows?.length){revBusy=true;try{const r=await req('/functions/v1/revisados-final',{method:'POST',body:'{}'});if(r.data?.ok){cache=r.data;window.__v106RevisadosCache=r.data}}catch(_){return}finally{revBusy=false}}const rows=(cache?.rows||[]).filter(r=>!r.emitido);if(!rows.length)return;bar.dataset.v154Smart='1';const ids=['v66OP','v66OG','v66OM','v66OS','v66OL','v66OB','v66OF'],get={v66OP:r=>N(r.prioridad),v66OG:r=>N(r.galera),v66OM:r=>String(r.mes_num||''),v66OS:r=>String(r.supervisora||''),v66OL:r=>String(r.status2||''),v66OB:r=>N(r.situacion),v66OF:r=>r.fotos_disponibles?'SI':'NO'},labels={v66OP:'Todas las prioridades',v66OG:'Todas las galeras',v66OM:'Todos los meses',v66OS:'Todas las supervisoras',v66OL:'Todos Estatus 2',v66OB:'Situación: todas',v66OF:'Fotos: todas'},month=new Map([...document.querySelector('#v66OM')?.options||[]].map(o=>[o.value,o.textContent]));function match(r,ignore){const qq=N(document.querySelector('#v66OQ')?.value);if(qq&&!N([r.unidad,r.placa,r.empresa,r.cupo_control,r.supervisora,r.status2].join(' ')).includes(qq))return false;for(const id of ids){if(id===ignore)continue;const el=document.getElementById(id);if(!el||el.type==='hidden'||!el.value)continue;if(String(get[id](r))!==String(el.value))return false}return true}function sync(){ids.forEach(id=>{const el=document.getElementById(id);if(!el||el.type==='hidden')return;const cur=el.value,vals=[...new Set(rows.filter(r=>match(r,id)).map(get[id]).filter(Boolean))].sort((a,b)=>id==='v66OM'?Number(a)-Number(b):String(a).localeCompare(String(b),'es'));el.innerHTML='<option value="">'+labels[id]+'</option>'+vals.map(x=>'<option value="'+E(x)+'">'+E(id==='v66OM'?(month.get(String(x))||x):x)+'</option>').join('');if([...el.options].some(o=>o.value===cur))el.value=cur;else el.value=''})}bar.addEventListener('change',()=>setTimeout(sync,0));document.querySelector('#v66OQ')?.addEventListener('input',()=>setTimeout(sync,0));sync()}

 async function hook(){setTimeout(enhanceRev,80)}
 if(!w.RYM_REVISADOS_ROUTER?.after)throw new Error('Revisados router hook API unavailable');
 w.RYM_REVISADOS_ROUTER.routes().forEach(route=>w.RYM_REVISADOS_ROUTER.after(route,hook));
})(window);
