
(function(){
'use strict';
const V166E=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const V166N=v=>String(v??'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
let opCache=null,opAt=0,opBusy=null;
async function operationalMap(){if(opCache&&Date.now()-opAt<60000)return opCache;if(opBusy)return opBusy;opBusy=(async()=>{try{const rows=await rpc('panapass_estados_operativos');const m=new Map((rows||[]).map(x=>[V166N(x.unidad),x]));opCache=m;opAt=Date.now();return m}finally{opBusy=null}})();return opBusy}
function opLabel(x){if(!x)return'';const e=V166N(x.estado_operativo),s=String(x.status2||'').trim();if(e==='ABONO ADICIONAL')return'Abono adicional';if(e==='PARADO')return s&&V166N(s)!=='ACTIVO'?`Parado · ${s}`:'Parado';return''}
async function decoratePanTables(root=document){if(!document.querySelector('.shell')||document.body.classList.contains('v70-control')||document.body.classList.contains('v66-revisados'))return;let m;try{m=await operationalMap()}catch{return}root.querySelectorAll('table tbody tr').forEach(tr=>{if(tr.dataset.v166Op==='1')return;const unitCell=tr.querySelector('td[data-label="Unidad"]'),unit=V166N(unitCell?.querySelector('b')?.textContent||unitCell?.childNodes?.[0]?.textContent||unitCell?.textContent);if(!unit)return;const x=m.get(unit),label=opLabel(x);if(!label){tr.dataset.v166Op='1';return}const statusCell=tr.querySelector('td[data-label="Estatus"]')||unitCell;if(!statusCell)return;const d=document.createElement('small');d.className='v166-op-context '+(V166N(x.estado_operativo)==='ABONO ADICIONAL'?'abono':'parado');d.textContent=label;statusCell.appendChild(d);tr.dataset.v166Op='1'})}
function cleanPanDashboard(){if(document.body.classList.contains('v70-control')||document.body.classList.contains('v66-revisados'))return;document.querySelector('#view .ca6-dashboard-card')?.remove()}
const oldDash166=typeof dashboard==='function'?dashboard:null;if(oldDash166){dashboard=async function(v){const r=await oldDash166.apply(this,arguments);cleanPanDashboard();return r}}
['negativos','pagos','pagosConsultaHoy','pagosTrabajo'].forEach(name=>{try{const old=globalThis[name];if(typeof old!=='function'||old.__v166)return;const fn=async function(){const r=await old.apply(this,arguments);setTimeout(()=>decoratePanTables(document.querySelector('#view')||document),20);return r};fn.__v166=true;globalThis[name]=fn;try{eval(name+'=fn')}catch(_){}}catch(_){}});

/* Revisados Operations: robust dependent filters based on the current V2/V165 data cache. */
async function revRows(){let c=window.__v106RevisadosCache;if(c?.rows?.length)return c.rows.filter(r=>!r.emitido);try{const z=await req('/functions/v1/revisados-final',{method:'POST',body:'{}'});if(z.data?.ok){window.__v106RevisadosCache=z.data;return (z.data.rows||[]).filter(r=>!r.emitido)}}catch(_){}return[]}
async function smartRev166(){const bar=document.querySelector('body.v66-revisados .v66-filterbar');if(!bar||!document.querySelector('#v66OP')||bar.dataset.v166Smart)return;bar.dataset.v166Smart='loading';let rows=[];try{rows=await revRows()}catch(_){delete bar.dataset.v166Smart;return}if(!rows.length){delete bar.dataset.v166Smart;return}bar.dataset.v166Smart='1';const ids=['v66OP','v66OG','v66OM','v66OS','v66OL','v66OB','v66OF'];const getters={v66OP:r=>V166N(r.prioridad),v66OG:r=>V166N(r.galera),v66OM:r=>String(r.mes_num||''),v66OS:r=>String(r.supervisora||''),v66OL:r=>String(r.status2||''),v66OB:r=>V166N(r.situacion||(r.bloqueado?'BLOQUEADO':'LISTO')),v66OF:r=>r.fotos_disponibles?'SI':'NO'};const labels={v66OP:'Todas las prioridades',v66OG:'Todas las galeras',v66OM:'Todos los meses',v66OS:'Todas las supervisoras',v66OL:'Todos Estatus 2',v66OB:'Situación: todas',v66OF:'Fotos: todas'};const monthNames=['','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
 function matches(r,ignore){const q=V166N(document.querySelector('#v66OQ')?.value);if(q&&!V166N([r.unidad,r.placa,r.empresa,r.cupo_control,r.supervisora,r.status2].join(' ')).includes(q))return false;for(const id of ids){if(id===ignore)continue;const el=document.getElementById(id);if(!el||el.type==='hidden'||!el.value)continue;if(String(getters[id](r))!==String(el.value))return false}return true}
 function sync(){for(const id of ids){const el=document.getElementById(id);if(!el||el.type==='hidden')continue;const cur=el.value;let vals=[...new Set(rows.filter(r=>matches(r,id)).map(getters[id]).filter(Boolean))];vals.sort((a,b)=>id==='v66OM'?Number(a)-Number(b):String(a).localeCompare(String(b),'es'));el.innerHTML=`<option value="">${labels[id]}</option>`+vals.map(x=>`<option value="${V166E(x)}">${V166E(id==='v66OM'?(monthNames[Number(x)]||x):x)}</option>`).join('');el.value=[...el.options].some(o=>o.value===cur)?cur:''}}
 bar.addEventListener('change',()=>setTimeout(sync,0));document.querySelector('#v66OQ')?.addEventListener('input',()=>setTimeout(sync,0));sync();
}

/* Manual V2 consultation for Revisados. */
function v2Cats(b={}){const ena=Number(b?.infraccionesEna?.cantidad||0),doc=Number(b?.boletasPorDocumento?.cantidad||0),pla=Number(b?.boletasPorPlaca?.cantidad||0);return{ena,doc,pla,html:`<div class="v166-v2-cats"><div class="v166-v2-cat ${ena?'warn':''}"><span>Infracciones ENA</span><b>${ena}</b></div><div class="v166-v2-cat ${doc?'warn':''}"><span>Boletas documento</span><b>${doc}</b></div><div class="v166-v2-cat ${pla?'warn':''}"><span>Boletas placa</span><b>${pla}</b></div></div>`}}
function vehicleHtml(v={}){const fields=[['Placa',v.nroPlaca],['Propietario',v.nombrePropietario],['Documento',v.nroDocumentoPropietario],['Cupo',v.cupo||'—'],['Revisado',v.fechaRevisado],['RevId',v.revId],['Color',v.colorVehiculo],['Estado',v.estadoVehiculo],['Marca / modelo',[v.marcaVehiculo,v.modeloVehiculo].filter(Boolean).join(' ')],['VIN',v.nroVin||v.nroChasis]];return`<div class="v166-v2-vehicle">${fields.map(([a,b])=>`<div class="v166-v2-field"><span>${V166E(a)}</span><b>${V166E(b||'—')}</b></div>`).join('')}</div>`}
async function pollManual166(id,out,badge){for(let i=0;i<45;i++){const z=await req('/functions/v1/revisados-ecarcheck-v2-manual',{method:'POST',body:JSON.stringify({action:'STATUS',queue_id:id})});const d=z.data;if(!d?.ok)throw Error(d?.error||'No se pudo consultar el estado');const st=V166N(d.queue?.estado);badge.textContent=st==='PENDIENTE'?'Esperando puente V2':st==='PROCESANDO'?'Consultando eCarCheck V2':st;badge.className='v166-v2-live '+(['ERROR','SESION_REQUERIDA'].includes(st)?'bad':(['PENDIENTE','PROCESANDO','BLOQUEADO'].includes(st)?'wait':''));if(d.done){const r=d.result||{},cats=v2Cats(r.boletas||{}),block=r.bloqueo?.errors?.[0];out.innerHTML=cats.html+(r.vehiculo?vehicleHtml(r.vehiculo):'')+(block?`<div class="v166-v2-block"><b>${V166E(block.title||'Bloqueado')}</b><br>${V166E(block.detail||r.detalle||'')}</div>`:(st==='ERROR'||st==='SESION_REQUERIDA'?`<div class="v166-v2-block"><b>${V166E(d.queue?.error_code||st)}</b><br>${V166E(d.queue?.error_detail||'')}</div>`:''));return}await new Promise(r=>setTimeout(r,2000))}throw Error('La consulta sigue pendiente; verifica que la extensión V2 esté conectada.')}
function injectManual166(){if(!document.body.classList.contains('v66-revisados')||!document.querySelector('#v66OP'))return;const body=document.querySelector('#v66Body');if(!body||body.querySelector('#v166V2Manual'))return;const box=document.createElement('section');box.id='v166V2Manual';box.className='v166-v2-manual';box.innerHTML=`<div class="v166-v2-manual-head"><div><h3>Consulta puntual eCarCheck V2</h3><p>Ficha oficial + ENA + boletas por documento + boletas por placa, sin usar credenciales V1.</p></div><span id="v166V2Badge" class="v166-v2-live">V2 listo</span></div><div class="v166-v2-tools"><input id="v166V2Plate" maxlength="12" placeholder="Placa"><button id="v166V2Go">Consultar V2</button></div><div id="v166V2Out" class="v166-v2-result"></div>`;body.prepend(box);const input=box.querySelector('#v166V2Plate'),go=box.querySelector('#v166V2Go'),out=box.querySelector('#v166V2Out'),badge=box.querySelector('#v166V2Badge');go.onclick=async()=>{const placa=V166N(input.value).replace(/\s+/g,'');if(!/^[A-Z0-9-]{3,12}$/.test(placa)){out.innerHTML='<div class="v166-v2-block">Placa inválida.</div>';return}go.disabled=true;out.innerHTML='';badge.textContent='Encolando…';badge.className='v166-v2-live wait';try{const z=await req('/functions/v1/revisados-ecarcheck-v2-manual',{method:'POST',body:JSON.stringify({action:'START',placa})});if(!z.data?.ok)throw Error(z.data?.error||'No se pudo iniciar');await pollManual166(z.data.queue_id,out,badge)}catch(e){badge.textContent='Error';badge.className='v166-v2-live bad';out.innerHTML=`<div class="v166-v2-block">${V166E(e.message||e)}</div>`}finally{go.disabled=false}};input.onkeydown=e=>{if(e.key==='Enter')go.click()}}

/* V2 company boleta validator: independent ENA / document / plate signals. */
let boletaFilter166='TODAS',boletaCompanies166=[];
function boletaResult166(g){const checks=g?.checks||[];return checks.some(x=>Number(x.ena||0)>0||Number(x.documento||0)>0||Number(x.placa_boleta||0)>0)?'CON BOLETA':'SIN BOLETA'}
function renderBoletaCompanies166(companies=[]){boletaCompanies166=companies;const f=boletaFilter166||'TODAS',rows=companies.filter(g=>f==='TODAS'||boletaResult166(g)===f),tools=`<div class="v166-boleta-tools"><button type="button" data-v166f="TODAS" class="${f==='TODAS'?'active':''}">Todas</button><button type="button" data-v166f="CON BOLETA" class="${f==='CON BOLETA'?'active':''}">Con boleta</button><button type="button" data-v166f="SIN BOLETA" class="${f==='SIN BOLETA'?'active':''}">Sin boleta</button></div>`;if(!companies.length)return tools+'<div class="v66-empty">Sin resultados V2 todavía.</div>';return tools+`<div class="v166-boleta-row head"><div>Empresa</div><div>Placas modelo</div><div>Resultado</div></div>`+rows.map(g=>{const res=boletaResult166(g),plates=(g.checks||[]).map(x=>V166E(x.placa||'—')).join(' · ');return`<div class="v166-boleta-row"><div><b>${V166E(g.galera||'')} · ${V166E(g.empresa||'')}</b></div><div>${plates||'—'}</div><div class="v166-result ${res==='CON BOLETA'?'yes':'no'}">${res}</div></div>`}).join('')}
function bindBoletaFilters166(out){out?.querySelectorAll('[data-v166f]').forEach(b=>{b.onclick=()=>{boletaFilter166=b.dataset.v166f||'TODAS';out.innerHTML=renderBoletaCompanies166(boletaCompanies166);bindBoletaFilters166(out)}})}
async function pollBoletas166(runId,box){localStorage.setItem('rym_v166_boletas_run',runId);const st=box.querySelector('#v166BoletaStatus'),out=box.querySelector('#v166BoletaOut');for(let i=0;i<120;i++){const z=await req('/functions/v1/revisados-boletas-v2',{method:'POST',body:JSON.stringify({action:'STATUS',run_id:runId})}),d=z.data;if(!d?.ok)throw Error(d?.error||'Error consultando lote V2');st.textContent=`${d.procesadas||0}/${d.total||0} procesadas`;out.innerHTML=renderBoletaCompanies166(d.companies||[]);bindBoletaFilters166(out);if(d.done){st.textContent=`Finalizado · ${d.procesadas}/${d.total}`;window.__v106RevisadosCache=null;return d}await new Promise(r=>setTimeout(r,2500))}throw Error('El lote continúa en proceso.')}
function injectBoletas166(){if(!document.body.classList.contains('v66-revisados')||!document.querySelector('#v66BoletaSync'))return;const body=document.querySelector('#v66Body');if(!body||body.querySelector('#v166BoletasV2'))return;const box=document.createElement('section');box.id='v166BoletasV2';box.className='v166-boletas-v2';box.innerHTML=`<div class="v166-boletas-v2-head"><div><h3>Boletas · 16 empresas</h3><small>2 placas activas aleatorias por empresa. Resultado simple: con boleta o sin boleta.</small></div><div><span id="v166BoletaStatus" style="font-size:9px;font-weight:900;margin-right:8px">Listo</span><button id="v166BoletaStart">Actualizar V2</button></div></div><div id="v166BoletaOut"></div>`;body.prepend(box);const old=document.querySelector('#v66BoletaSync');if(old){old.style.display='none'}const btn=box.querySelector('#v166BoletaStart'),st=box.querySelector('#v166BoletaStatus');btn.onclick=async()=>{if(!confirm('¿Consultar 2 placas activas de cada una de las 16 empresas usando eCarCheck V2?'))return;btn.disabled=true;st.textContent='Creando lote…';try{const z=await req('/functions/v1/revisados-boletas-v2',{method:'POST',body:JSON.stringify({action:'START'})});if(!z.data?.ok)throw Error(z.data?.error||'No se pudo iniciar');await pollBoletas166(z.data.run_id,box)}catch(e){st.textContent=e.message||String(e)}finally{btn.disabled=false}};const last=localStorage.getItem('rym_v166_boletas_run');if(last)pollBoletas166(last,box).catch(()=>{})}


/* Positive-balance transfer form: ADMIN_TOTAL only, PDF is generated server-side with audited signature. */
function enhanceBajasPdf166(){if(V166N(state?.profile?.rol)!=='ADMIN_TOTAL')return;const body=document.querySelector('#v99BBody');if(!body)return;body.querySelectorAll('tbody tr').forEach(tr=>{if(tr.querySelector('[data-v166-pdf]'))return;const action=tr.querySelector('[data-v99ba][data-id]');if(!action)return;const saldoTxt=tr.querySelector('td[data-label="Saldo"]')?.textContent||'',m=saldoTxt.match(/([0-9]+(?:\.[0-9]{1,2})?)/);if(!m||Number(m[1])<=0)return;const td=action.closest('td');if(!td)return;const b=document.createElement('button');b.className='soft-btn';b.dataset.v166Pdf=action.dataset.id;b.textContent='Formulario firmado';b.style.marginLeft='6px';b.onclick=async()=>{b.disabled=true;const old=b.textContent;b.textContent='Generando…';try{const r=await fetch(URL+'/functions/v1/panapass-baja-transferencia-pdf',{method:'POST',headers:{...H(),'content-type':'application/json'},body:JSON.stringify({baja_id:Number(b.dataset.v166Pdf)})});if(!r.ok){let msg=await r.text();try{msg=JSON.parse(msg)?.error||msg}catch{}throw Error(msg||('HTTP '+r.status))}const blob=await r.blob(),a=document.createElement('a'),cd=r.headers.get('content-disposition')||'',fm=cd.match(/filename="?([^";]+)"?/i);a.href=window.URL.createObjectURL(blob);a.download=fm?.[1]||'Transferencia_saldo_positivo.pdf';document.body.appendChild(a);a.click();setTimeout(()=>{window.URL.revokeObjectURL(a.href);a.remove()},1000);b.textContent='Generado ✓'}catch(e){alert(e.message||e);b.textContent=old;b.disabled=false}};td.appendChild(b)})}
function revEnhance166(){smartRev166().catch(()=>{});injectManual166();injectBoletas166();enhanceBajasPdf166()}

const mo=new MutationObserver(()=>{cleanPanDashboard();decoratePanTables(document.querySelector('#view')||document).catch(()=>{});revEnhance166()});mo.observe(document.documentElement,{childList:true,subtree:true});setTimeout(()=>{cleanPanDashboard();decoratePanTables().catch(()=>{});revEnhance166()},100);
})();
