(function(){
  if(window.__RYM_V157_GPS__)return;window.__RYM_V157_GPS__=true;
  const E=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const N=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
  const F=v=>{if(!v)return '—';try{return new Intl.DateTimeFormat('es-PA',{timeZone:'America/Panama',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(_){return String(v)}};
  const R={tab:'dashboard',data:null,page:1,auditPage:1,loading:false,focus:'',rankGal:'TODAS'};
  const role=()=>N(state?.profile?.rol||'');
  const canGps=()=>{const mods=new Set([...(state?.allModules||[]),...(state?.modules||[])].map(String));return mods.has('portal.gps')||mods.has('gps.dashboard')||role()==='ADMIN_TOTAL'};
  const gpsClass=r=>{if(r?.historico)return 'HISTORICO';const inst=Number(r?.instalados||0),rep=Number(r?.reportando||0);if(inst===0)return 'CRITICO';if(rep===0)return 'CRITICO';if(inst===2&&rep===1)return 'ALERTA';return 'OK'};
  const gpsReason=r=>{const c=gpsClass(r),inst=Number(r?.instalados||0),rep=Number(r?.reportando||0);if(c==='HISTORICO')return r?.razon||'Histórico GPS';if(c==='CRITICO')return inst===0?'Sin GPS instalado':'Ningún GPS reporta';if(c==='ALERTA')return '1 de 2 GPS reportando';if(inst===1&&rep===1)return '1 GPS instalado y reportando';return '2 GPS reportando'};
  const hasData=r=>Number(r?.instalados||0)>0;
  const reporting=r=>!!(r?.gps1?.ok||r?.gps2?.ok);
  const priorityRows=()=>allRows().filter(r=>!r.historico&&N(r.estado_operativo)==='ACTIVO');
  const operationalRows=()=>allRows().filter(r=>!r.historico);
  const historicalRows=()=>allRows().filter(r=>r.historico);
  const allRows=()=>Array.isArray(R.data?.rows)?R.data.rows:[];
  const qsel=s=>document.querySelector(s);
  function toast(t){document.querySelector('.v157-toast')?.remove();const d=document.createElement('div');d.className='v157-toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
  function copyText(t){const done=()=>toast('Reporte copiado');if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(t).then(done).catch(()=>fallback());function fallback(){const a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();try{document.execCommand('copy');done()}catch(_){toast('No se pudo copiar')}a.remove()}}
  function filterBase(rows,{operation=true,audit=false}={}){const q=N(qsel('#v157Q')?.value||''),gal=N(qsel('#v157Gal')?.value||'TODAS'),sup=N(qsel('#v157Sup')?.value||'TODAS'),st=N(qsel('#v157State')?.value||'TODOS'),lev=N(qsel('#v157Level')?.value||'TODOS');return rows.filter(r=>{if(q&&!N([r.unidad,r.placa,r.empresa,r.supervisora,r.galera,r.estatus_interno].join(' ')).includes(q))return false;if(gal!=='TODAS'&&N(r.galera)!==gal)return false;if(sup!=='TODAS'&&N(r.supervisora)!==sup)return false;if(operation&&st!=='TODOS'&&N(r.estado_operativo)!==st)return false;if(operation&&lev!=='TODOS'&&gpsClass(r)!==lev)return false;if(audit&&st!=='TODOS'&&N(r.estado_operativo)!==st)return false;return true})}
  function options(){const rows=allRows(),g=qsel('#v157Gal'),s=qsel('#v157Sup');if(!g||!s)return;const oldG=g.value||'TODAS',oldS=s.value||'TODAS',gals=[...new Set(rows.map(r=>String(r.galera||'').trim()).filter(Boolean))].sort(),galSel=N(oldG);g.innerHTML='<option value="TODAS">Todas las galeras</option>'+gals.map(x=>'<option value="'+E(x)+'">'+E(x)+'</option>').join('');if([...g.options].some(o=>o.value===oldG))g.value=oldG;const scope=galSel==='TODAS'?rows:rows.filter(r=>N(r.galera)===galSel),sups=[...new Set(scope.map(r=>String(r.supervisora||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));s.innerHTML='<option value="TODAS">Todas las supervisoras</option>'+sups.map(x=>'<option value="'+E(x)+'">'+E(x)+'</option>').join('');if([...s.options].some(o=>o.value===oldS))s.value=oldS}
  function pill(text,tone='neutral'){return '<span class="v157-pill '+tone+'">'+E(text)+'</span>'}
  function gpsPill(g){if(!g?.installed)return pill('SIN GPS','neutral');if(g.ok)return pill('REPORTA','good');return pill(g.label||'NO REPORTA','bad')}
  function opPill(v){const x=N(v);return pill(v||'—',x==='ACTIVO'?'good':x==='ABONO ADICIONAL'?'blue':x==='PARADO'?'warn':'neutral')}
  function diagPill(r){const c=gpsClass(r);return pill(c,c==='CRITICO'?'bad':c==='ALERTA'?'warn':c==='OK'?'good':'neutral')}
  function tableRows(rows,audit=false){return rows.map(r=>'<tr><td><b>'+E(r.unidad||'—')+'</b><span class="v157-sub">'+E(r.empresa||'')+'</span></td><td>'+E(r.galera||'—')+'</td><td>'+E(r.supervisora||'—')+'</td><td>'+opPill(r.estado_operativo)+'</td><td>'+gpsPill(r.gps1)+'<span class="v157-sub">'+E(F(r.gps1?.last))+'</span></td><td>'+gpsPill(r.gps2)+'<span class="v157-sub">'+E(F(r.gps2?.last))+'</span></td>'+(audit?'<td>'+pill(r.estatus_interno||'SIN ESTATUS','blue')+'</td><td><b>'+E(F(r.ultima_fecha))+'</b></td>':'<td>'+diagPill(r)+'<span class="v157-sub">'+E(gpsReason(r))+'</span></td><td>'+E(r.velocidad===''?'—':String(r.velocidad)+' km/h')+'</td>')+'<td>'+(r.mapa?'<a class="v157-map" href="'+E(r.mapa)+'" target="_blank">Ver mapa</a>':'—')+'</td></tr>').join('')}
  function pager(page,pages,total,kind='main'){const from=total?(page-1)*50+1:0,to=Math.min(page*50,total);return '<div class="v157-pager"><span>'+from+'–'+to+' de '+total+'</span><div><button data-v157-page="'+kind+':-1" '+(page<=1?'disabled':'')+'>← Anterior</button><span>Página '+page+' / '+pages+'</span><button data-v157-page="'+kind+':1" '+(page>=pages?'disabled':'')+'>Siguiente →</button></div></div>'}
  function bindPager(root,render){root.querySelectorAll('[data-v157-page]').forEach(b=>b.onclick=()=>{const [kind,delta]=b.dataset.v157Page.split(':');if(kind==='audit')R.auditPage+=Number(delta);else R.page+=Number(delta);render()})}
  function ranking(rows){const m=new Map();rows.forEach(r=>{const name=r.supervisora||'SIN SUPERVISORA',key=N(r.galera)+'|'+N(name),z=m.get(key)||{name,galera:r.galera,total:0,crit:0,alert:0,ok:0};z.total++;const c=gpsClass(r);if(c==='CRITICO')z.crit++;else if(c==='ALERTA')z.alert++;else z.ok++;m.set(key,z)});return [...m.values()].map(z=>({...z,problems:z.crit+z.alert,rate:z.total?((z.crit+z.alert)/z.total*100):0})).sort((a,b)=>a.problems-b.problems||a.crit-b.crit||b.total-a.total||a.name.localeCompare(b.name,'es'))}
  function peerRanking(){
    const p=R.peer;
    if(!p||!Array.isArray(p.rows))return [];
    return p.rows.map(z=>({id:z.supervisora_id||null,name:z.supervisora||'SIN SUPERVISORA',galera:z.galera||'',total:Number(z.total||0),crit:Number(z.criticos||0),alert:Number(z.alertas||0),ok:Number(z.ok||0),problems:Number(z.problemas||0),rate:Number(z.total||0)?Number(z.problemas||0)/Number(z.total||0)*100:0}));
  }
  function displayRanking(rows){return role()==='SUPERVISORA'?peerRanking():ranking(rows)}
  function peerPosition(){const p=R.peer||{};return {position:Number(p.position||0),total:Number(p.total||0),me:p.me||null,galera:p.galera||''}}
  async function loadPeerRanking(){
    if(role()!=='SUPERVISORA'){R.peer=null;return}
    try{
      const r=await req('/functions/v1/gps-ranking-galera',{method:'POST',body:'{}'});
      if(r?.data?.ok){R.peer=r.data;if(R.tab==='dashboard'||R.tab==='ranking')render()}
    }catch(_){R.peer={error:true,rows:[]}}
  }
  function reportText(rows){
    const list=ranking(rows),now=new Date(),date=new Intl.DateTimeFormat('es-PA',{timeZone:'America/Panama',day:'2-digit',month:'2-digit',year:'numeric'}).format(now),time=new Intl.DateTimeFormat('es-PA',{timeZone:'America/Panama',hour:'numeric',minute:'2-digit',hour12:true}).format(now),total=rows.length,crit=rows.filter(r=>gpsClass(r)==='CRITICO').length,alert=rows.filter(r=>gpsClass(r)==='ALERTA').length,pending=crit+alert,gals=[...new Set(rows.map(r=>String(r.galera||'').trim()).filter(Boolean))],scope=gals.length===1?gals[0]:'GENERAL',medals=['1️⃣','2️⃣','3️⃣','4️⃣','5️⃣'];
    let t='📡 *GPS · REPORTE DE SUPERVISORAS*\n🗓️ '+date+' · 🕘 '+time+'\n🎯 *Prioridad:* unidades ACTIVO con incidencias GPS\n\n📊 *'+scope+'*\n🚗 '+total+' activas\n';
    if(crit>0)t+='🚨 '+crit+' crítica'+(crit===1?'':'s')+'\n';
    if(alert>0)t+='⚠️ '+alert+' alerta'+(alert===1?'':'s')+'\n';
    t+='📌 '+pending+' pendiente'+(pending===1?'':'s')+' GPS\n\n🏆 *Ranking de atención*\n';
    list.forEach((z,i)=>{const gal=gals.length===1?'':' · '+(z.galera||''),parts=['📌 '+z.problems+' pendiente'+(z.problems===1?'':'s')];if(z.crit>0)parts.push('🚨 '+z.crit+' crítica'+(z.crit===1?'':'s'));if(z.alert>0)parts.push('⚠️ '+z.alert+' alerta'+(z.alert===1?'':'s'));parts.push('🚗 '+z.total+' activas');t+=(medals[i]||(i+1)+'.')+' *'+z.name+'*'+gal+' — '+parts.join(' · ')+'\n'});
    t+='\n🚨 *Crítica* = atención inmediata\n⚠️ *Alerta* = prevención / revisar pronto';
    return t
  }
  function renderDashboard(){
    const root=qsel('#v157View');if(!root)return;
    const base=filterBase(priorityRows()),crit=base.filter(r=>gpsClass(r)==='CRITICO'),alert=base.filter(r=>gpsClass(r)==='ALERTA'),ok=base.filter(r=>gpsClass(r)==='OK'),sin=base.filter(r=>Number(r.instalados||0)===0),g1=base.filter(r=>!r.gps1?.ok),g2=base.filter(r=>!r.gps2?.ok),problems=[...crit,...alert].sort((a,b)=>(gpsClass(a)==='CRITICO'?0:1)-(gpsClass(b)==='CRITICO'?0:1)||String(a.unidad).localeCompare(String(b.unidad),'es',{numeric:true})),rank=displayRanking(base),hist=historicalRows(),closedNow=hist.filter(r=>N(r.estado_operativo)==='CERRADO'&&reporting(r)),par=operationalRows().filter(r=>N(r.estado_operativo)==='PARADO').length,abo=operationalRows().filter(r=>N(r.estado_operativo)==='ABONO ADICIONAL').length;
    const pp=peerPosition();
    let performance='';
    if(role()==='SUPERVISORA'){
      if(pp.position&&pp.me){
        const me=pp.me,probs=Number(me.problemas||0),mc=Number(me.criticos||0),ma=Number(me.alertas||0),tot=Number(me.total||0);
        performance='<div class="v163-my-rank"><span>HOY · TU GALERA</span><strong>#'+pp.position+' / '+pp.total+'</strong><b>'+E(pp.galera||me.galera||'')+'</b><p>'+probs+' pendiente'+(probs===1?'':'s')+' GPS · '+mc+' crítica'+(mc===1?'':'s')+' · '+ma+' alerta'+(ma===1?'':'s')+' · '+tot+' activas</p><small>Menos pendientes GPS = mejor posición entre tus compañeras.</small></div>';
      }else performance='<div class="v157-empty">Comparando tu resultado con las supervisoras de tu galera…</div>';
    }else{
      performance=rank.slice(0,10).map((z,i)=>'<div class="v157-prio"><div><b>'+(i<3?['🥇 ','🥈 ','🥉 '][i]:'')+E(z.name)+'</b><span>'+E(z.galera)+' · '+z.total+' activas</span></div><div>'+pill(z.problems+' pendientes GPS',z.problems===0?'good':z.crit?'bad':'warn')+'</div></div>').join('')||'<div class="v157-empty">Sin supervisoras para estos filtros.</div>';
    }
    root.innerHTML='<div class="v157-kpis"><article class="v157-kpi bad" data-focus="CRITICO"><span>Críticos · ACTIVO</span><b>'+crit.length+'</b><small>Atención inmediata</small></article><article class="v157-kpi warn" data-focus="ALERTA"><span>Alertas · ACTIVO</span><b>'+alert.length+'</b><small>1 de 2 GPS reportando</small></article><article class="v157-kpi bad" data-focus="SINGPS"><span>Sin GPS · ACTIVO</span><b>'+sin.length+'</b><small>Sin GPS1 ni GPS2</small></article><article class="v157-kpi" data-focus="GPS1"><span>GPS1 con incidencia</span><b>'+g1.length+'</b><small>Sin instalar o no reporta</small></article><article class="v157-kpi" data-focus="GPS2"><span>GPS2 con incidencia</span><b>'+g2.length+'</b><small>Sin instalar o no reporta</small></article><article class="v157-kpi good" data-focus="OK"><span>GPS operación OK</span><b>'+ok.length+'</b><small>Sin problema GPS</small></article></div><div class="v157-substats"><span class="v157-chip">ACTIVO: <b>'+base.length+'</b></span><span class="v157-chip">PARADO: <b>'+par+'</b></span><span class="v157-chip">ABONO ADICIONAL: <b>'+abo+'</b></span><span class="v157-chip">CERRADAS reportando: <b>'+closedNow.length+'</b></span></div><div class="v158-action-order"><div class="critical"><b>1</b><span><strong>Críticos: '+crit.length+'</strong><small>Atender primero: sin GPS o ningún GPS reportando.</small></span></div><div class="warning"><b>2</b><span><strong>Alertas: '+alert.length+'</strong><small>Después: 2 GPS instalados y solo 1 reportando.</small></span></div><div class="audit"><b>3</b><span><strong>Auditoría: '+closedNow.length+'</strong><small>Cerradas reportando; separadas del ranking diario.</small></span></div></div><div class="v157-grid2"><section class="v157-card"><div class="v157-card-head"><div><h3>Prioridades GPS · unidades ACTIVO</h3><p>Críticos primero; después alertas. Esta es la lista operativa principal.</p></div><strong>'+problems.length+'</strong></div><div class="v157-table-wrap"><table class="v157-table"><thead><tr><th>Unidad</th><th>Galera</th><th>Supervisora</th><th>Estado</th><th>GPS1</th><th>GPS2</th><th>Diagnóstico</th><th>Velocidad</th><th>Mapa</th></tr></thead><tbody>'+(tableRows(problems.slice(0,80))||'<tr><td colspan="9"><div class="v157-empty">Sin problemas GPS en unidades ACTIVO.</div></td></tr>')+'</tbody></table></div></section><section class="v157-card"><div class="v157-card-head"><div><h3>'+(role()==='SUPERVISORA'?'Tu posición GPS':'Mejor desempeño GPS')+'</h3><p>'+(role()==='SUPERVISORA'?'Comparación real contra tu galera.':'Pendientes GPS = Críticos + Alertas. Menos pendientes = mejor posición.')+'</p></div>'+(role()==='SUPERVISORA'?'':'<button class="v157-btn soft" id="v157CopyDash">Copiar reporte</button>')+'</div><div class="v157-priority">'+performance+'</div></section></div>';
    const cp=qsel('#v157CopyDash');if(cp)cp.onclick=()=>copyText(reportText(base));root.querySelectorAll('[data-focus]').forEach(k=>k.onclick=()=>{R.focus=k.dataset.focus;R.tab='fleet';R.page=1;setNav();const st=qsel('#v157State');if(st)st.value='ACTIVO';render()})
  }
  function renderFleet(){const root=qsel('#v157View');if(!root)return;let rows=filterBase(operationalRows());if(R.focus){const f=R.focus;rows=rows.filter(r=>f==='SINGPS'?Number(r.instalados||0)===0:f==='GPS1'?!r.gps1?.ok:f==='GPS2'?!r.gps2?.ok:gpsClass(r)===f)}rows.sort((a,b)=>({CRITICO:0,ALERTA:1,OK:2}[gpsClass(a)]??3)-({CRITICO:0,ALERTA:1,OK:2}[gpsClass(b)]??3)||String(a.unidad).localeCompare(String(b.unidad),'es',{numeric:true}));const pages=Math.max(1,Math.ceil(rows.length/50));R.page=Math.max(1,Math.min(R.page,pages));const slice=rows.slice((R.page-1)*50,R.page*50);root.innerHTML='<section class="v157-card"><div class="v157-card-head"><div><h3>Flota GPS</h3><p>ACTIVO, PARADO y ABONO ADICIONAL. Usa los filtros superiores para auditar cada grupo.</p></div><div class="v157-card-actions">'+(R.focus?'<button class="v157-btn soft" id="v157ClearFocus">Quitar filtro KPI</button>':'')+'<strong>'+rows.length+'</strong></div></div><div class="v157-table-wrap"><table class="v157-table"><thead><tr><th>Unidad</th><th>Galera</th><th>Supervisora</th><th>Estado operativo</th><th>GPS1</th><th>GPS2</th><th>Diagnóstico</th><th>Velocidad</th><th>Mapa</th></tr></thead><tbody>'+(tableRows(slice)||'<tr><td colspan="9"><div class="v157-empty">Sin resultados.</div></td></tr>')+'</tbody></table></div>'+pager(R.page,pages,rows.length)+'</section>';qsel('#v157ClearFocus')&&(qsel('#v157ClearFocus').onclick=()=>{R.focus='';renderFleet()});bindPager(root,renderFleet)}
  function renderRanking(){
    const root=qsel('#v157View');if(!root)return;const rows=filterBase(priorityRows()),list=displayRanking(rows),max=Math.max(1,...list.map(x=>x.problems)),pp=peerPosition();
    if(role()==='SUPERVISORA'&&!R.peer){root.innerHTML='<section class="v157-card"><div class="v157-empty">Comparando tu resultado con las supervisoras de tu galera…</div></section>';return}
    root.innerHTML='<section class="v157-card"><div class="v157-card-head"><div><h3>Ranking GPS de supervisoras</h3><p>Solo unidades ACTIVO. Pendientes GPS = Críticos + Alertas; menos pendientes = mejor posición.</p></div><div class="v157-card-actions">'+(role()==='SUPERVISORA'&&pp.position?'<span class="v163-rank-chip">Tu posición: <b>#'+pp.position+' / '+pp.total+'</b></span>':'<button class="v157-btn green" id="v157CopyRank">Copiar texto</button>')+'<strong>'+list.length+'</strong></div></div><div class="v157-ranking"><div class="v157-rank head"><span>#</span><span>Supervisora</span><span>Activas</span><span>Críticos</span><span>Alertas</span><span>Pendientes GPS</span><span>% afectadas</span></div>'+list.map((z,i)=>{const mine=role()==='SUPERVISORA'&&R.peer?.me&&String(R.peer.me.supervisora_id||'')===String(z.id||'');return '<div class="v157-rank '+(mine?'v163-rank-me':'')+'"><span class="place">'+(i<3?['🥇','🥈','🥉'][i]:i+1)+'</span><span><b>'+E(z.name)+'</b><small class="v157-sub">'+E(z.galera)+'</small></span><span class="score">'+z.total+'</span><span class="score problem">'+z.crit+'</span><span class="score alert">'+z.alert+'</span><span class="score '+(z.problems===0?'ok':'problem')+'">'+z.problems+'</span><span><div class="v157-progress"><i style="width:'+Math.round(z.problems/max*100)+'%"></i></div><small class="v157-sub">'+z.rate.toFixed(1)+'%</small></span></div>'}).join('')+'</div><div class="v157-copybox"><b>Pendientes GPS</b> significa Críticos + Alertas. El ranking no cuenta PARADO, ABONO ADICIONAL, CERRADO ni CANIBALIZADO: mide solo unidades ACTIVO. Para SUPERVISORA, solo se comparten totales agregados de sus compañeras; nunca sus unidades.</div></section>';const cp=qsel('#v157CopyRank');if(cp)cp.onclick=()=>copyText(reportText(rows))
  }
  function renderAudit(){const root=qsel('#v157View');if(!root)return;let rows=filterBase(historicalRows().filter(hasData),{operation:false,audit:true});const cond=N(qsel('#v157AuditCond')?.value||'TODOS');if(cond==='REPORTANDO')rows=rows.filter(reporting);if(cond==='HISTORIAL')rows=rows.filter(r=>!reporting(r));rows.sort((a,b)=>(reporting(b)?1:0)-(reporting(a)?1:0)||(new Date(b.ultima_fecha||0)-new Date(a.ultima_fecha||0)));const all=filterBase(historicalRows().filter(hasData),{operation:false,audit:true}),closed=all.filter(r=>N(r.estado_operativo)==='CERRADO'),cani=all.filter(r=>N(r.estado_operativo)==='CANIBALIZADO'),closedRep=closed.filter(reporting),caniRep=cani.filter(reporting);const pages=Math.max(1,Math.ceil(rows.length/50));R.auditPage=Math.max(1,Math.min(R.auditPage,pages));const slice=rows.slice((R.auditPage-1)*50,R.auditPage*50);root.innerHTML='<div class="v157-audit-banner"><b>Auditoría separada de la operación.</b> Aquí aparecen únicamente unidades CERRADAS o CANIBALIZADAS que todavía conservan información GPS. Nunca aumentan los críticos/alertas ni afectan el ranking diario.</div><div class="v157-audit-kpis"><article class="v157-kpi bad"><span>Cerradas reportando</span><b>'+closedRep.length+'</b><small>Transmisión en últimas 24 h</small></article><article class="v157-kpi purple"><span>Fuera de operación con datos</span><b>'+all.length+'</b><small>Cerradas + canibalizadas</small></article><article class="v157-kpi"><span>Canibalizadas con datos</span><b>'+cani.length+'</b><small>Historial GPS disponible</small></article><article class="v157-kpi warn"><span>Canibalizadas reportando</span><b>'+caniRep.length+'</b><small>Debe ser 0 idealmente</small></article></div><section class="v157-card"><div class="v157-card-head"><div><h3>Auditoría GPS de unidades fuera de operación</h3><p>Solo unidades con GPS o historial. Revisar primero las que continúan transmitiendo.</p></div><div class="v157-card-actions"><select id="v157AuditCond" style="border:1px solid #cad9ea;border-radius:10px;padding:8px"><option value="TODOS">Todas con información</option><option value="REPORTANDO">Reportando ahora</option><option value="HISTORIAL">Solo historial</option></select><strong>'+rows.length+'</strong></div></div><div class="v157-table-wrap"><table class="v157-table"><thead><tr><th>Unidad</th><th>Galera</th><th>Supervisora</th><th>Control</th><th>GPS1</th><th>GPS2</th><th>Estatus fuente</th><th>Última GPS</th><th>Mapa</th></tr></thead><tbody>'+(tableRows(slice,true)||'<tr><td colspan="9"><div class="v157-empty">Sin resultados.</div></td></tr>')+'</tbody></table></div>'+pager(R.auditPage,pages,rows.length,'audit')+'</section>';const sel=qsel('#v157AuditCond');sel.value=cond;sel.onchange=()=>{R.auditPage=1;renderAudit()};bindPager(root,renderAudit)}
  function renderExecutive(){
    const root=qsel('#v157View');if(!root)return;
    if(role()!=='ADMIN_TOTAL'){root.innerHTML='<section class="v157-card"><div class="v157-empty">Ejecutivo GPS está disponible únicamente para ADMIN_TOTAL.</div></section>';return}
    const rows=filterBase(operationalRows(),{operation:false}),states=['ACTIVO','PARADO','ABONO ADICIONAL'];
    const summarize=list=>{const installed=[0,0,0],reporting=[0,0,0],matrix=[[0,0,0],[0,0,0],[0,0,0]];list.forEach(r=>{const i=Math.max(0,Math.min(2,Number(r.instalados||0))),p=Math.max(0,Math.min(2,Number(r.reportando||0)));installed[i]++;reporting[p]++;matrix[i][p]++});return{total:list.length,installed,reporting,matrix}};
    const total=summarize(rows),metric=(title,a,kind)=>'<div class="v160-dist '+kind+'"><b>'+E(title)+'</b><div><span><strong>'+a[0]+'</strong><small>0 GPS</small></span><span><strong>'+a[1]+'</strong><small>1 GPS</small></span><span><strong>'+a[2]+'</strong><small>2 GPS</small></span></div></div>',matrix=m=>'<div class="v160-matrix"><table><thead><tr><th>Instalados ↓ / Reportando →</th><th>0</th><th>1</th><th>2</th></tr></thead><tbody>'+[0,1,2].map(i=>'<tr><th>'+i+' GPS</th>'+[0,1,2].map(p=>'<td class="'+(p===0?'bad':p===2?'good':'warn')+'"><b>'+m[i][p]+'</b></td>').join('')+'</tr>').join('')+'</tbody></table></div>';
    const card=st=>{const list=rows.filter(r=>N(r.estado_operativo)===st),z=summarize(list),tone=st==='ACTIVO'?'active':st==='PARADO'?'stopped':'extra';return '<section class="v160-exec-state '+tone+'"><div class="v160-exec-head"><div><span>'+E(st)+'</span><h3>'+z.total+' unidades</h3></div><small>Instalación y transmisión GPS</small></div>'+metric('GPS instalados',z.installed,'installed')+metric('GPS reportando',z.reporting,'reporting')+matrix(z.matrix)+'</section>'};
    const galMap=new Map();rows.forEach(r=>{const g=String(r.galera||'SIN GALERA').trim()||'SIN GALERA';if(!galMap.has(g))galMap.set(g,[]);galMap.get(g).push(r)});
    const gals=[...galMap.entries()].map(([gal,list])=>{const z=summarize(list),activo=list.filter(r=>N(r.estado_operativo)==='ACTIVO').length,parado=list.filter(r=>N(r.estado_operativo)==='PARADO').length,abono=list.filter(r=>N(r.estado_operativo)==='ABONO ADICIONAL').length,double=z.total?z.reporting[2]/z.total*100:0,coverage=z.total?(z.reporting[1]+z.reporting[2])/z.total*100:0;return{gal,total:z.total,activo,parado,abono,ins:z.installed,rep:z.reporting,double,coverage}}).sort((a,b)=>N(a.gal)==='SIN GALERA'?1:N(b.gal)==='SIN GALERA'?-1:a.gal.localeCompare(b.gal,'es'));
    const realGals=gals.filter(g=>N(g.gal)!=='SIN GALERA'),sinGalera=gals.find(g=>N(g.gal)==='SIN GALERA'),galLabel=realGals.length+' galeras'+(sinGalera?' · '+sinGalera.total+' sin galera':'');
    const galTable='<section class="v157-card v163-gal-card"><div class="v157-card-head"><div><h3>Visión ejecutiva por galera</h3><p>Compara estructura operativa, instalación y transmisión GPS entre galeras.</p></div><strong>'+galLabel+'</strong></div><div class="v163-gal-table"><table><thead><tr><th>Galera</th><th>Total</th><th>Activo</th><th>Parado</th><th>Abono</th><th>0 GPS</th><th>1 GPS</th><th>2 GPS</th><th>0 reporta</th><th>1 reporta</th><th>2 reportan</th><th>% cobertura GPS</th><th>% doble GPS</th></tr></thead><tbody>'+gals.map(g=>'<tr><td><b>'+E(g.gal)+'</b></td><td><b>'+g.total+'</b></td><td>'+g.activo+'</td><td>'+g.parado+'</td><td>'+g.abono+'</td><td class="bad">'+g.ins[0]+'</td><td class="warn">'+g.ins[1]+'</td><td class="good">'+g.ins[2]+'</td><td class="bad">'+g.rep[0]+'</td><td class="warn">'+g.rep[1]+'</td><td class="good">'+g.rep[2]+'</td><td><b>'+g.coverage.toFixed(1)+'%</b></td><td><b>'+g.double.toFixed(1)+'%</b></td></tr>').join('')+'</tbody></table></div></section>';
    root.innerHTML='<section class="v157-card v160-exec-intro"><div class="v157-card-head"><div><h3>Ejecutivo GPS · cobertura real de flota</h3><p>Solo ADMIN_TOTAL. Universo operativo: ACTIVO, PARADO y ABONO ADICIONAL. CERRADO y CANIBALIZADO permanecen exclusivamente en Auditoría.</p></div><strong>'+rows.length+' unidades</strong></div><div class="v160-exec-global">'+metric('GPS instalados · total',total.installed,'installed')+metric('GPS reportando · total',total.reporting,'reporting')+'</div></section><div class="v160-exec-grid">'+states.map(card).join('')+'</div>'+galTable
  }
  function setNav(){
    document.querySelectorAll('[data-v157-tab]').forEach(b=>b.classList.toggle('active',b.dataset.v157Tab===R.tab));
    const stateSel=qsel('#v157State'),level=qsel('#v157Level');
    if(R.tab==='audit'){
      stateSel.innerHTML='<option value="TODOS">Cerradas + canibalizadas</option><option value="CERRADO">Cerradas</option><option value="CANIBALIZADO">Canibalizadas</option>';
      level.style.display='none';stateSel.disabled=false;
    }else{
      stateSel.innerHTML='<option value="TODOS">Todos los estados</option><option value="ACTIVO">Activo</option><option value="PARADO">Parado</option><option value="ABONO ADICIONAL">Abono adicional</option>';
      level.style.display=R.tab==='executive'?'none':'block';
      if(R.tab==='dashboard'||R.tab==='ranking'){stateSel.value='ACTIVO';stateSel.disabled=true}
      else if(R.tab==='executive'){stateSel.value='TODOS';stateSel.disabled=true}
      else stateSel.disabled=false;
    }
    options();
  }
  function render(){if(R.tab==='dashboard')renderDashboard();else if(R.tab==='fleet')renderFleet();else if(R.tab==='ranking')renderRanking();else if(R.tab==='audit')renderAudit();else renderExecutive()}
  async function load(){
    if(R.loading)return;R.loading=true;const root=qsel('#v157View');if(root)root.innerHTML='<section class="v157-card"><div class="v157-empty">Consultando GPS en vivo…</div></section>';
    try{
      const r=await req('/functions/v1/gps-rym-admin',{method:'POST',body:JSON.stringify({q:'',galera:'TODAS',estado:'TODOS',nivel:'TODOS',onlyProblems:false})});if(!r?.data?.ok)throw Error(r?.data?.error||'No se pudo consultar GPS');R.data=r.data;R.peer=null;
      allRows().forEach(x=>{if(!x.historico){x.nivel=gpsClass(x);x.razon=gpsReason(x)}});window.__v164GpsPortalData={key:[state?.profile?.id||'',state?.profile?.email||'',state?.profile?.supervisora_id||'',N(state?.profile?.rol||'')].join('|'),data:R.data};
      R.page=1;R.auditPage=1;options();render();const src=R.data?.source_counts||{},scope=R.data?.scope||{};const live=qsel('#v157Live');if(live)live.textContent='GPS en vivo · '+Number(src.gps_records||0)+' registros · '+Number(scope.visible_units||0)+' unidades en alcance';
      if(role()==='SUPERVISORA')loadPeerRanking();
    }catch(e){if(root)root.innerHTML='<div class="alert">'+E(e.message||e)+'</div>'}finally{R.loading=false}
  }
  async function openGps(){if(!canGps())return;R.tab='dashboard';R.focus='';R.page=1;R.auditPage=1;window.__RYM_ROUTE_V155='GPS';document.querySelectorAll('#v139HomeTransition,#v123PortalTransition,#v125PortalTransition,#v145LoginTransition').forEach(x=>x.remove());document.body.className='v157-gps';app.innerHTML='<div class="v157-shell"><aside class="v157-side"><div class="v157-brand"><div class="v157-brand-icon">⌖</div><div><b>GPS RYM</b><small>Centro de Control</small></div></div><nav class="v157-nav"><button data-v157-tab="dashboard" class="active"><i>▦</i>Dashboard</button><button data-v157-tab="fleet"><i>⌖</i>Flota GPS</button><button data-v157-tab="ranking"><i>🏆</i>Ranking</button><button data-v157-tab="audit"><i>✓</i>Auditoría</button>'+(role()==='ADMIN_TOTAL'?'<button data-v157-tab="executive"><i>▤</i>Ejecutivo</button>':'')+'</nav><div class="v157-side-foot">Perfil: <b>'+E(state.profile?.rol||'')+'</b><br>El alcance se aplica en backend.<button class="v157-back" id="v157Back">← Volver al Portal</button></div></aside><main class="v157-main"><header class="v157-top"><div class="v157-top-row"><div class="v157-title"><h1>GPS · Centro de Control</h1><p>Prioridad diaria: unidades ACTIVO · GPS1 + GPS2 · alertas reales por perfil</p></div><div class="v157-live" id="v157Live">Conectando GPS…</div></div></header><div class="v157-content"><section class="v157-toolbar"><input id="v157Q" placeholder="Buscar unidad, placa, empresa o supervisora"><select id="v157Gal"><option value="TODAS">Todas las galeras</option></select><select id="v157Sup"><option value="TODAS">Todas las supervisoras</option></select><select id="v157State"><option value="TODOS">Todos los estados</option></select><select id="v157Level"><option value="TODOS">Todos los diagnósticos</option><option value="CRITICO">Críticos</option><option value="ALERTA">Alertas</option><option value="OK">OK</option></select><button id="v157Refresh">Actualizar</button></section><div id="v157View"></div></div></main><nav class="v157-mobile-nav"><button data-v157-tab="dashboard" class="active">Dashboard</button><button data-v157-tab="fleet">Flota</button><button data-v157-tab="ranking">Ranking</button><button data-v157-tab="audit">Auditoría</button>'+(role()==='ADMIN_TOTAL'?'<button data-v157-tab="executive">Ejecutivo</button>':'')+'</nav></div>';
    qsel('#v157Back').onclick=()=>{window.__RYM_ROUTE_V155='PORTAL';window.v36PortalHome?.()};document.querySelectorAll('[data-v157-tab]').forEach(b=>b.onclick=()=>{R.tab=b.dataset.v157Tab;R.focus='';R.page=1;R.auditPage=1;setNav();render()});qsel('#v157Refresh').onclick=load;qsel('#v157Q').oninput=()=>{R.page=1;R.auditPage=1;render()};qsel('#v157Gal').onchange=()=>{R.page=1;R.auditPage=1;options();render()};qsel('#v157Sup').onchange=()=>{R.page=1;R.auditPage=1;render()};qsel('#v157State').onchange=()=>{R.page=1;R.auditPage=1;render()};qsel('#v157Level').onchange=()=>{R.page=1;render()};setNav();await load()}
  openGps.__v157=true;window.v113OpenGps=openGps;try{v113OpenGps=openGps}catch(_){}
})();
