<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { revisadosService, type RevisadosNavItem } from '../services/revisados.service'
import type { CanonicalRevisadoRow, CanonicalRevisadosResponse, RevisadoRecord } from '../types/revisados.types'
import { useRevisados } from '../composables/useRevisados'
import MissionControlSummary from '../components/MissionControlSummary.vue'
import GaleraComparison from '../components/GaleraComparison.vue'
import RevisadosFilterBar from '../components/RevisadosFilterBar.vue'
import RevisadosTable from '../components/RevisadosTable.vue'

const data=ref<CanonicalRevisadosResponse>(), records=ref<RevisadoRecord[]>([]), loading=ref(true), error=ref(''), active=ref('dashboard')
const profile=ref({nombre:'Portal RYM',rol:'',scope_label:''}), navItems=ref<RevisadosNavItem[]>([])
const {filters,filtered,metrics,options,clearFilters}=useRevisados(records)
const rawRows=computed(()=>Array.isArray(data.value?.rows)?data.value.rows as CanonicalRevisadoRow[]:[])
const pending=computed(()=>rawRows.value.filter(r=>!r.emitido))
const emitted=computed(()=>Array.isArray((data.value?.emitidos_hoy as {rows?:CanonicalRevisadoRow[]}|undefined)?.rows)?(data.value?.emitidos_hoy as {rows:CanonicalRevisadoRow[]}).rows:[])
const monthly=computed(()=>Array.isArray(data.value?.monthly)?data.value.monthly as Array<Record<string,unknown>>:[])
const gallery=computed(()=>Array.isArray(data.value?.por_galera)?data.value.por_galera as Array<Record<string,unknown>>:[])
const selectedGalera=ref(''), selectedStatus=ref('')
function text(v:unknown){return String(v??'—')}
function num(v:unknown){return new Intl.NumberFormat('es-PA').format(Number(v)||0)}
function date(v:unknown){try{return v?new Intl.DateTimeFormat('es-PA',{dateStyle:'medium'}).format(new Date(String(v))):'—'}catch{return text(v)}}
function state(r:CanonicalRevisadoRow){return r.emitido?'Vigente':r.requiere_atencion?'Pendiente':'Sin ciclo'}
function status(r:CanonicalRevisadoRow){return r.bloqueado?'Bloqueo real':String(r.pendiente_tipo||r.status2||state(r))}
const visibleRows=computed(()=>pending.value.filter(r=>(!selectedGalera.value||text(r.galera)===selectedGalera.value)&&(!selectedStatus.value||text(r.status2)===selectedStatus.value)))
const galeras=computed(()=>[...new Set(rawRows.value.map(r=>text(r.galera)).filter(x=>x!=='—'))].sort())
const statuses=computed(()=>[...new Set(pending.value.map(r=>text(r.status2)).filter(x=>x!=='—'))].sort())
async function load(force=false){loading.value=true;error.value='';try{const response=await revisadosService.load(force);data.value=response;records.value=await revisadosService.list();profile.value={nombre:response.profile?.nombre||'Portal RYM',rol:response.profile?.rol||'',scope_label:response.profile?.scope_label||''};navItems.value=revisadosService.context().tabs; if(!navItems.value.some(x=>x.id===active.value))active.value='dashboard'}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{loading.value=false}}
function open(id:string){if(navItems.value.some(x=>x.id===id))active.value=id}
function copyPending(){navigator.clipboard?.writeText(visibleRows.value.map(r=>[r.unidad,r.placa,r.galera,r.supervisora,status(r)].join(' | ')).join('\n'))}
onMounted(()=>load())
</script>

<template>
<main class="rym-revisados-vue">
  <aside class="rv-side"><div class="rv-brand"><img src="https://drive.google.com/thumbnail?id=1f65vwdwsAraUrK2h7cb5l_eVOQKuHsL8&sz=w1000" alt="RYM"><div><b>Revisados RYM</b><small>Control legal vehicular</small></div></div><div class="rv-user"><b>{{profile.nombre}}</b><span>{{profile.rol}}</span><small>{{profile.scope_label}}</small></div><nav><button v-for="item in navItems" :key="item.id" :class="{active:active===item.id}" @click="open(item.id)"><i>{{item.icon}}</i>{{item.label}}</button></nav><button class="rv-back" @click="revisadosService.back()">← Volver al Portal</button></aside>
  <section class="rv-main"><header><div><small>REVISADOS / {{ active.toUpperCase() }}</small><h1>{{navItems.find(x=>x.id===active)?.label}}</h1></div><div><button class="ghost" @click="clearFilters">Limpiar filtros</button><button class="primary" :disabled="loading" @click="load(true)">{{loading?'Actualizando…':'Actualizar vista'}}</button></div></header>
    <div v-if="loading" class="rv-state">Cargando datos reales de Revisados…</div><div v-else-if="error" class="rv-state error"><b>No fue posible cargar Revisados.</b><span>{{error}}</span><button class="primary" @click="load(true)">Reintentar</button></div>
    <template v-else>
      <section v-if="active==='dashboard'" class="rv-stack"><div class="rv-intro"><span>MISSION CONTROL</span><h2>Control legal de la flota</h2><p>Indicadores y prioridades de tu alcance autorizado.</p></div><MissionControlSummary :total="metrics.total" :vigentes="metrics.vigentes" :pendientes="metrics.pendientesCiclo" :cambios-color="metrics.cambiosColor" :incidencias="metrics.incidencias"/><RevisadosFilterBar v-model="filters" :galeras="options.galeras" :supervisoras="options.supervisoras"/><GaleraComparison :rows="filtered"/><RevisadosTable :rows="filtered"/></section>
      <section v-else-if="active==='operations'" class="rv-stack"><div class="rv-filters"><input v-model="filters.search" placeholder="Buscar unidad, placa o empresa"><select v-model="selectedGalera"><option value="">Todas las galeras</option><option v-for="x in galeras" :key="x">{{x}}</option></select><select v-model="selectedStatus"><option value="">Todos los estatus</option><option v-for="x in statuses" :key="x">{{x}}</option></select><button class="ghost" @click="copyPending">Copiar lista</button></div><p class="rv-note">{{num(visibleRows.length)}} pendientes reales en la cola operativa.</p><div class="rv-table"><table><thead><tr><th>Unidad</th><th>Placa</th><th>Galera</th><th>Supervisora</th><th>Último revisado</th><th>Prioridad</th><th>Estado</th><th>Motivo</th></tr></thead><tbody><tr v-for="r in visibleRows" :key="String(r.unidad_id||r.unidad)"><td>{{r.unidad}}</td><td>{{r.placa}}</td><td>{{r.galera}}</td><td>{{r.supervisora||'—'}}</td><td>{{date(r.ultimo_revisado)}}</td><td>{{r.prioridad||'—'}}</td><td><b :class="{danger:r.bloqueado}">{{state(r)}}</b></td><td>{{status(r)}}</td></tr></tbody></table></div></section>
      <section v-else-if="active==='monthly'" class="rv-stack"><div class="rv-grid"><article v-for="m in monthly.filter(x=>Number(x.pendientes||0)||Number(x.cubiertas||0))" :key="String(m.mes_num)" class="rv-card"><b>{{m.mes_nombre||`Mes ${m.mes_num}`}}</b><strong>{{num(m.cubiertas)}} / {{num(m.total||m.activas)}} al día</strong><span>{{num(m.pendientes)}} pendientes</span></article></div><div class="rv-table"><table><thead><tr><th>Galera</th><th>Total</th><th>Al día</th><th>Pendientes</th></tr></thead><tbody><tr v-for="g in gallery" :key="String(g.galera)"><td>{{g.galera}}</td><td>{{num(g.total)}}</td><td>{{num(g.cubiertas)}}</td><td>{{num(g.pendientes)}}</td></tr></tbody></table></div></section>
      <section v-else-if="active==='daily'" class="rv-stack"><div class="rv-grid"><article class="rv-card"><b>Emitidos hoy</b><strong>{{num(emitted.length)}}</strong></article><article class="rv-card"><b>Pendientes</b><strong>{{num(pending.length)}}</strong></article></div><h3>Emitidos hoy</h3><div class="rv-table"><table><thead><tr><th>Unidad</th><th>Placa</th><th>Galera</th><th>Empresa</th><th>Último revisado</th></tr></thead><tbody><tr v-for="r in emitted" :key="String(r.unidad_id||r.placa)"><td>{{r.unidad}}</td><td>{{r.placa}}</td><td>{{r.galera}}</td><td>{{r.empresa}}</td><td>{{date(r.ultimo_revisado)}}</td></tr></tbody></table></div></section>
      <section v-else-if="active==='history'" class="rv-stack"><RevisadosFilterBar v-model="filters" :galeras="options.galeras" :supervisoras="options.supervisoras"/><RevisadosTable :rows="filtered"/></section>
      <section v-else-if="active==='stats'" class="rv-stack"><div class="rv-grid"><article class="rv-card"><b>Cobertura</b><strong>{{metrics.total?Math.round(metrics.vigentes/metrics.total*100):0}}%</strong></article><article class="rv-card"><b>Alertas reales</b><strong>{{metrics.incidencias}}</strong></article><article class="rv-card"><b>Cambio de color</b><strong>{{metrics.cambiosColor}}</strong></article></div><GaleraComparison :rows="filtered"/></section>
      <section v-else-if="active==='boletas'" class="rv-stack"><p class="rv-note">Boletas y restricciones reales detectadas por la fuente canónica.</p><div class="rv-table"><table><thead><tr><th>Unidad</th><th>Placa</th><th>Empresa</th><th>Galera</th><th>Restricción</th></tr></thead><tbody><tr v-for="r in rawRows.filter(x=>Array.isArray(x.alerts)&&x.alerts.length)" :key="String(r.unidad_id||r.placa)"><td>{{r.unidad}}</td><td>{{r.placa}}</td><td>{{r.empresa}}</td><td>{{r.galera}}</td><td>{{(r.alerts||[]).map(x=>x.tipo||x.texto).join(' · ')}}</td></tr></tbody></table></div></section>
      <section v-else class="rv-state"><b>Cupos</b><span>La información de compras de cupos se mantiene en su fuente canónica. Esta pantalla queda disponible sin cambiar a legacy.</span></section>
    </template>
  </section>
</main>
</template>

<style scoped>
.rym-revisados-vue{min-height:100vh;display:grid;grid-template-columns:240px minmax(0,1fr);background:#f6f8fb;color:#17243a;font:14px Inter,system-ui,sans-serif}.rv-side{min-height:100vh;padding:18px 12px;background:#fff;border-right:1px solid #e5eaf1;display:flex;flex-direction:column}.rv-brand{display:flex;gap:10px;align-items:center;padding:4px 7px 18px}.rv-brand img{width:38px;height:38px;object-fit:contain}.rv-brand b,.rv-user b{display:block}.rv-brand small,.rv-user span,.rv-user small{display:block;color:#718097;font-size:11px;margin-top:3px}.rv-user{padding:12px;background:#f6f9fd;border:1px solid #e2e8f1;border-radius:11px;margin-bottom:16px}nav{display:grid;gap:4px}nav button,.rv-back{border:0;background:transparent;text-align:left;padding:11px;border-radius:9px;color:#52627a;font-weight:700}nav button i{display:inline-block;width:23px;font-style:normal}nav button.active{background:#eaf3ff;color:#0062ff}.rv-back{margin-top:auto;border-top:1px solid #e5eaf1;border-radius:0}.rv-main{padding:28px;min-width:0}.rv-main>header{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:22px}.rv-main h1,.rv-main h2{margin:4px 0}.rv-main header small,.rv-intro span{font-size:10px;letter-spacing:.1em;color:#0062ff;font-weight:800}.primary,.ghost{border-radius:8px;padding:9px 12px;font-weight:800;border:1px solid #d5deeb;background:#fff;color:#31425c}.primary{background:#0062ff;color:#fff;border-color:#0062ff}.rv-stack{display:grid;gap:14px}.rv-intro,.rv-card,.rv-table,.rv-state,.rv-note,.rv-filters{background:#fff;border:1px solid #e1e7ef;border-radius:12px;padding:16px}.rv-intro p{color:#67768b;margin:5px 0 0}.rv-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.rv-card{display:grid;gap:7px}.rv-card strong{font-size:25px}.rv-card span,.rv-note{color:#68788d}.rv-filters{display:flex;gap:8px;flex-wrap:wrap}.rv-filters input,.rv-filters select{padding:9px;border:1px solid #d5deeb;border-radius:8px}.rv-filters input{min-width:220px}.rv-table{overflow:auto;padding:0}.rv-table table{border-collapse:collapse;width:100%;min-width:760px}.rv-table th,.rv-table td{padding:11px;border-bottom:1px solid #edf0f4;text-align:left;font-size:12px}.rv-table th{color:#617187;background:#fafbfd}.danger{color:#c2352b}.rv-state{display:grid;gap:9px;place-items:start}.error{border-color:#efb7b2}@media(max-width:780px){.rym-revisados-vue{grid-template-columns:1fr}.rv-side{min-height:auto}.rv-main{padding:16px}.rv-main>header{align-items:flex-start;flex-direction:column}}
</style>
