/* Portal RYM - Panapass Dashboard V2 Clean presentation components. */
(function(w){
  'use strict';
  if(w.RYM_PANAPASS_CLEAN_COMPONENTS)return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const integer=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:0});
  const money=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
  const pct=n=>Number(n||0).toLocaleString('es-PA',{maximumFractionDigits:1});
  const nameOf=x=>String(x?.supervisora_nombre||x?.supervisora||x?.nombre||'—');
  const avg=arr=>arr?.length?arr.reduce((a,x)=>a+Number(x.amount||0),0)/arr.length:0;

  function header(vm,title,subtitle){return `<header class="rym-pdc-header"><div class="rym-pdc-heading"><div class="rym-pdc-eyebrow"><b>PANAPASS</b><span>${esc(vm.phase==='PM'?'CIERRE PM':'OPERACION AM')}</span></div><h1>${esc(title)}</h1><p>${esc(subtitle||'')}</p></div><div class="rym-pdc-head-actions"><div><small>HOY</small><strong>${esc(vm.date)}</strong><em>Datos en vivo</em></div><button type="button" data-pdc-action="refresh">↻ Actualizar</button></div></header>`}
  function kpi(label,value,note,tone,icon){return `<article class="rym-pdc-kpi rym-pdc-tone-${esc(tone)}"><div class="rym-pdc-kpi-icon">${esc(icon)}</div><div><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(note)}</span></div></article>`}
  function kpiStrip(vm){return `<section class="rym-pdc-kpis">${[
    ['Unidades activas',integer(vm.kpis.active),'Bajo tu alcance','blue','▦'],
    ['Negativos hoy',integer(vm.kpis.negatives),vm.phase==='AM'?'Prioridad AM':'Seguimiento del dia','red','!'],
    ['Requirieron pago',integer(vm.kpis.requiredPayment),'Unidades del dia','green','$'],
    ['Monto pagado hoy','B/. '+money(vm.kpis.paidAmount),'Resultado de cobranza','teal','✓'],
    ['Sin Panapass',integer(vm.kpis.noPanapass),'Pendientes por asignar','orange','○'],
    ['Bajas Panapass',integer(vm.kpis.bajas),'Pendientes de gestion','purple','↓']
  ].map(x=>kpi(...x)).join('')}</section>`}
  function sectionTitle(title,subtitle,side){return `<div class="rym-pdc-section-title"><div><h2>${esc(title)}</h2>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div>${side||''}</div>`}
  function pendingPanel(vm){const rows=[['Sin Panapass',vm.kpis.noPanapass,'orange'],['Bajas',vm.kpis.bajas,'purple'],['Recurrentes',vm.kpis.recurrentes,'blue']];return `<section class="rym-pdc-card rym-pdc-pending">${sectionTitle(vm.phase==='AM'?'Requieren tu atencion':'Pendientes prioritarios',vm.phase==='AM'?'Incidencias que conviene resolver primero.':'Cierra el dia atendiendo lo pendiente.')}<div class="rym-pdc-pending-list">${rows.map(([a,b,c])=>`<div class="rym-pdc-pending-row"><i class="${c}"></i><span>${esc(a)}</span><strong>${integer(b)}</strong></div>`).join('')}</div></section>`}
  function performanceEntity(label,x,type,tone){if(!x)return `<article class="rym-pdc-performance ${tone}"><small>${esc(label)}</small><strong>Sin datos</strong><span>—</span></article>`;const sup=type==='supervisor';const name=sup?nameOf(x):x.galera;const units=sup?Number(x.unidades_pagadas||0):Number(x.paidUnits||0);const amount=sup?Number(x.monto_pagado||0):Number(x.paidAmount||0);return `<article class="rym-pdc-performance ${tone}"><small>${esc(label)}</small><strong>${esc(name)}</strong><span>${integer(units)} incidencias · B/. ${money(amount)}</span></article>`}
  function performancePanel(vm){const p=vm.performance||{};return `<section class="rym-pdc-card rym-pdc-performance-panel">${sectionTitle('Rendimiento destacado de hoy','Menor incidencia de pago representa mejor resultado operativo.')}<div class="rym-pdc-performance-grid">${performanceEntity('Mejor galera',p.bestGalera,'galera','good')}${performanceEntity('Mayor incidencia · galera',p.worstGalera,'galera','warn')}${performanceEntity('Mejor supervisora',p.bestSupervisor,'supervisor','good')}${performanceEntity('Mayor incidencia · supervisora',p.worstSupervisor,'supervisor','warn')}</div></section>`}
  function miniTrend(trend){const vals=(trend||[]).map(x=>Number(x.amount||0)),max=Math.max(1,...vals);return `<div class="rym-pdc-mini-bars">${vals.map((v,i)=>`<i style="--h:${Math.max(8,Math.round(v/max*100))}%" title="${esc(trend[i]?.date)} · B/. ${money(v)}"></i>`).join('')}</div>`}
  function galeraCard(g){return `<article class="rym-pdc-galera"><div class="rym-pdc-galera-head"><div><small>GALERA</small><h3>${esc(g.galera)}</h3></div><button type="button" data-pdc-galera="${esc(g.galera)}">Ver galera →</button></div><div class="rym-pdc-galera-stats"><div><small>Unidades</small><strong>${integer(g.units)}</strong></div><div><small>Negativos</small><strong>${integer(g.negatives)}</strong><em>B/. ${money(g.negativeAmount)}</em></div><div><small>Requirieron pago</small><strong>${integer(g.paidUnits)}</strong><em>B/. ${money(g.paidAmount)}</em></div></div>${miniTrend(g.trend)}<footer>Promedio 7 dias <b>B/. ${money(avg(g.trend))}</b></footer></article>`}
  function galeraGrid(vm){return `<section class="rym-pdc-section">${sectionTitle('Resumen por galera','Vista completa de la empresa.')}<div class="rym-pdc-galera-grid">${(vm.galeras||[]).map(galeraCard).join('')||'<div class="rym-pdc-empty">Sin datos de galeras.</div>'}</div></section>`}
  function rankTable(rows,options){const o=options||{},position=o.position||'posicion_global',me=String(o.meId||'');return `<div class="rym-pdc-rank"><div class="rym-pdc-rank-head"><span>#</span><span>Supervisora</span><span>Galera</span><span>Pagadas</span><span>Monto</span></div>${(rows||[]).map(x=>{const id=String(x.supervisora_id||x.id||''),mine=Boolean(me&&id===me);return `<div class="rym-pdc-rank-row ${mine?'is-me':''}"><b>#${integer(x[position]||0)}</b><span>${esc(nameOf(x))}${mine?'<small>Tu</small>':''}</span><span>${esc(x.galera||'—')}</span><strong>${integer(x.unidades_pagadas||0)}</strong><em>B/. ${money(x.monto_pagado||0)}</em></div>`}).join('')||'<div class="rym-pdc-empty">Sin datos de ranking.</div>'}</div>`}
  function trendPanel(title,trend){const vals=(trend||[]).map(x=>Number(x.units||0)),max=Math.max(1,...vals),total=vals.reduce((a,b)=>a+b,0);return `<section class="rym-pdc-card rym-pdc-trend">${sectionTitle(title,'Ultimos 7 dias')}<div class="rym-pdc-chart">${(trend||[]).map((x,i)=>`<div><b>${integer(x.units)}</b><i style="--h:${Math.max(7,Math.round(vals[i]/max*100))}%"></i><small>${esc(String(x.date||'').slice(5))}</small></div>`).join('')}</div><footer>Total 7 dias <strong>${integer(total)}</strong></footer></section>`}
  function companyComparison(vm){if(!vm.companyCompareAvailable)return `<section class="rym-pdc-card rym-pdc-comparison">${sectionTitle('Comparativo con la empresa','Comparacion agregada, sin acceso a otras operaciones.')}<div class="rym-pdc-empty compact">Comparativo agregado pendiente de habilitar en backend.</div></section>`;const rows=vm.companyComparison||[],mine=rows.find(x=>x.galera===vm.galera),avgPaid=rows.length?rows.reduce((a,x)=>a+Number(x.paidUnits||0),0)/rows.length:0;const ordered=[...rows].sort((a,b)=>Number(a.paidUnits||0)-Number(b.paidUnits||0)),pos=Math.max(0,ordered.findIndex(x=>x.galera===vm.galera))+1;return `<section class="rym-pdc-card rym-pdc-comparison">${sectionTitle('Comparativo con la empresa','Solo indicadores agregados.')}<div class="rym-pdc-compare-grid"><div><small>Posicion de ${esc(vm.galera)}</small><strong>#${integer(pos)} de ${integer(rows.length)}</strong></div><div><small>Tu galera</small><strong>${integer(mine?.paidUnits||0)}</strong><span>incidencias</span></div><div><small>Promedio empresa</small><strong>${pct(avgPaid)}</strong><span>incidencias</span></div></div></section>`}
  function quickActions(vm){return `<section class="rym-pdc-card rym-pdc-actions">${sectionTitle('Acciones rapidas','Abre solo pantallas dentro de tu alcance.')}<div>${[['Negativos',vm.actions.negatives,'!'],['Pagos',vm.actions.payments,'$'],['Bajas',vm.actions.bajas,'↓'],['Recurrentes',vm.actions.recurrentes,'↻']].map(([a,r,i])=>`<button type="button" data-pdc-route="${esc(r)}"><b>${esc(i)}</b><span>${esc(a)}</span></button>`).join('')}</div></section>`}
  function supervisorHero(vm){const s=vm.supervisorComparison||{};return `<section class="rym-pdc-super-hero"><div><small>MI PANAPASS</small><h2>Hola, ${esc(vm.name||'Supervisora')}</h2><p>${esc(vm.galera||'Tu galera')} · Gestion personal</p></div><div class="rym-pdc-super-metrics"><div><small>Posicion galera</small><strong>#${integer(s.localPosition||0)} <em>de ${integer(s.localTotal||0)}</em></strong></div><div><small>Posicion global</small><strong>#${integer(s.globalPosition||0)} <em>de ${integer(s.globalTotal||0)}</em></strong></div><div><small>Unidades activas</small><strong>${integer(vm.kpis.active)}</strong></div><div><small>Monto pagado hoy</small><strong>B/. ${money(vm.kpis.paidAmount)}</strong></div></div></section>`}
  function attentionTable(vm){return `<section class="rym-pdc-card rym-pdc-attention">${sectionTitle('Requiere atencion','Solo incidencias dentro de tu alcance.')}<div class="rym-pdc-attention-list">${(vm.alerts||[]).map(x=>`<div><span><b>${esc(x.unidad||'Unidad')}</b><small>${esc(x.placa||x.tipo||'')}</small></span><em>${esc(x.detalle||x.tipo||'Pendiente')}</em></div>`).join('')||'<div class="rym-pdc-empty compact">No hay incidencias detalladas pendientes.</div>'}</div></section>`}
  function supervisorComparison(vm){const s=vm.supervisorComparison||{};const diff=Number(s.myPaidUnits||0)-Number(s.galeraAverage||0);return `<section class="rym-pdc-card rym-pdc-super-compare">${sectionTitle('Comparacion vs promedio de galera','Contexto de rendimiento, sin acceso a unidades ajenas.')}<div><div><small>Tu incidencia</small><strong>${integer(s.myPaidUnits||0)}</strong></div><div><small>Promedio galera</small><strong>${pct(s.galeraAverage||0)}</strong></div><div><small>Diferencia</small><strong class="${diff<=0?'good':'warn'}">${diff>0?'+':''}${pct(diff)}</strong></div></div></section>`}

  w.RYM_PANAPASS_CLEAN_COMPONENTS=Object.freeze({esc,integer,money,header,kpiStrip,sectionTitle,pendingPanel,performancePanel,galeraGrid,rankTable,trendPanel,companyComparison,quickActions,supervisorHero,attentionTable,supervisorComparison});
})(window);
