/* Portal RYM - Panapass Dashboard V2 Supervisora view. Prepared, not wired. */
(function(w){
  'use strict';
  const V=w.RYM_PANAPASS_DASHBOARD_V2_VIEWS||(w.RYM_PANAPASS_DASHBOARD_V2_VIEWS={});
  if(V.supervisora)return;
  V.supervisora=function(vm){
    const C=w.RYM_PANAPASS_DASHBOARD_V2_COMPONENTS,s=vm.supervisorComparison||{},me=vm.ranking.me||{};
    const initials=String(vm.name||'S').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
    return `<main class="rym-pd2 rym-pd2-supervisora">${C.header(vm,'Mi Dashboard Panapass','Mi gestion diaria · Control de pagos y rendimiento en mi galera')}<section class="rym-pd2-personal-summary"><div class="rym-pd2-avatar">${C.esc(initials)}</div><div class="rym-pd2-who"><small>Hola,</small><strong>${C.esc(vm.name||'Supervisora')}</strong><span>Supervisora · ${C.esc(vm.galera||'')}</span></div><div><small>Mi posicion en la galera</small><strong>#${C.integer(s.localPosition||me.posicion_galera||0)}</strong><span>de ${C.integer(s.localTotal||me.total_galera||0)}</span></div><div><small>Posicion global</small><strong>#${C.integer(s.globalPosition||me.posicion_global||0)}</strong><span>de ${C.integer(s.globalTotal||me.total_global||0)}</span></div><div><small>Mis unidades activas</small><strong>${C.integer(vm.kpis.active)}</strong></div><div><small>Monto pagado hoy</small><strong>B/. ${C.money(vm.kpis.paidAmount)}</strong></div></section><section class="rym-pd2-kpi-grid five">${C.kpi('Mis negativos',C.integer(vm.kpis.negatives),'Referencia del dia','red','!')}${C.kpi('Requirieron pago',C.integer(vm.kpis.paidUnits),'En mis unidades','amber','$')}${C.kpi('Recurrentes',C.integer(vm.kpis.recurrentes),'En el mes','blue','↻')}${C.kpi('Sin Panapass',C.integer(vm.kpis.noPanapass),'En mis unidades','purple','—')}${C.kpi('Bajas / Pendientes',C.integer(vm.kpis.bajas),'En mi alcance','magenta','↓')}</section><div class="rym-pd2-two-col supervisor"><section class="rym-pd2-attention">${C.sectionTitle('Requiere atencion','Solo incidencias de tus unidades.')}<div class="rym-pd2-attention-list">${vm.alerts.map((x,i)=>`<article><b>${i+1}</b><span>${C.esc(x.unidad||x.placa||'Unidad')}</span><small>${C.esc(x.tipo)}</small><em>${C.esc(x.detalle)}</em></article>`).join('')||'<div class="rym-pd2-empty">Sin alertas abiertas.</div>'}</div></section><section class="rym-pd2-ranking">${C.sectionTitle('Mi ranking en la galera',`Supervisoras de ${vm.galera||'mi galera'}.`)}${C.rankTable(vm.ranking.local,{position:'posicion_galera',meId:vm.policy.identity.supervisoraId})}<aside class="rym-pd2-global-position"><small>Empresa</small><strong>#${C.integer(s.globalPosition||me.posicion_global||0)}</strong><span>de ${C.integer(s.globalTotal||me.total_global||0)} supervisoras</span><p>Comparacion global sin acceso a unidades ajenas.</p></aside></section></div><div class="rym-pd2-two-col">${C.trendPanel('Tendencia personal · 7 dias',vm.scopeTrend)}<section class="rym-pd2-compare-personal">${C.sectionTitle('Comparacion vs promedio de galera','Menos unidades pagadas representa mejor gestion.')}<div><article><small>Mis unidades pagadas</small><strong>${Number(s.myPaidUnits||0).toFixed(1)}</strong></article><article><small>Promedio de mi galera</small><strong>${Number(s.galeraAverage||0).toFixed(1)}</strong></article></div></section></div></main>`;
  };
})(window);

