/* Portal RYM V172 clean - Users application */
(function(w,d){
  'use strict';
  if(w.RYM_USERS_APP)return;
  function usersRole(){return String(state.profile?.rol||'').trim().toUpperCase()}
  function usersHasModule(code){
    if(typeof w.rymHasModule==='function')return !!w.rymHasModule(code);
    const all=Array.isArray(state.allModules)&&state.allModules.length?state.allModules:(Array.isArray(state.modules)?state.modules:[]);
    return all.includes(String(code));
  }
let AD=null,selected=null,adminView='users';
  const E=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const N=v=>String(v??'').trim().toUpperCase();
  const ROLES=['SUPERVISORA','GERENTE_GALERA','PAGADOR','OPERATIVO','ADMIN','SISTEMA','ADMIN_TOTAL'];
  const FIELDS=['puede_ver','puede_crear','puede_editar','puede_eliminar'];
  function toast(msg){let t=document.querySelector('#v70Toast');if(!t){t=document.createElement('div');t.id='v70Toast';t.className='v70-admin-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600)}
  async function adminApi(body){const r=await req('/functions/v1/admin-users',{method:'POST',body:JSON.stringify(body)});if(!r.data?.ok)throw Error(r.data?.error||'Error de administración');return r.data}
  async function adminLoad(){AD=await adminApi({action:'list'});return AD}
  function allowedTarget(roleName,code){const r=N(roleName),m=String(code||'').toLowerCase();if(m==='admin.usuarios'||m==='usuarios')return r==='ADMIN_TOTAL';return true}
  function options(vals,current){return vals.map(v=>`<option value="${E(v)}" ${String(v)===String(current)?'selected':''}>${E(v)}</option>`).join('')}
  function roleDefault(roleName,mod,field){return AD?.rol_permisos?.find(x=>N(x.rol)===N(roleName)&&String(x.modulo_codigo)===String(mod))?.[field]}
  function userOverride(uid,mod,field){const x=AD?.usuario_permisos?.find(x=>String(x.user_id)===String(uid)&&String(x.modulo_codigo)===String(mod));return x?x[field]:null}
  function permSelect(uid,roleName,mod,field,disabled){const ov=userOverride(uid,mod,field),def=roleDefault(roleName,mod,field),inh=def===true?'Heredado: Sí':def===false?'Heredado: No':'Heredado';return `<select data-perm-mod="${E(mod)}" data-perm-field="${field}" ${disabled?'disabled':''}><option value="" ${ov===null||ov===undefined?'selected':''}>${inh}</option><option value="true" ${ov===true?'selected':''}>Sí</option><option value="false" ${ov===false?'selected':''}>No</option></select>`}
  function scopeHtml(u){const supId=u.supervisoras?.[0]?.id||u.supervisora_id||'',gals=Array.isArray(u.galeras_scope)?u.galeras_scope:[];return `<div id="v70SupScope" class="v70-scope-box" style="display:${N(u.rol)==='SUPERVISORA'?'block':'none'}"><div class="v70-field"><label>Supervisora vinculada</label><select id="v70SupId"><option value="">Seleccionar...</option>${(AD.supervisoras||[]).map(s=>`<option value="${E(s.id)}" ${String(s.id)===String(supId)?'selected':''}>${E(s.nombre)} · ${E(s.galera)}</option>`).join('')}</select></div></div><div id="v70GalScope" class="v70-scope-box" style="display:${['ADMIN','GERENTE_GALERA'].includes(N(u.rol))?'block':'none'}"><div class="v70-field"><label>Galeras asignadas</label><div class="v70-checks">${(AD.galeras||[]).map(g=>`<label class="v70-check"><input type="checkbox" data-gal="${E(g)}" ${gals.includes(g)?'checked':''}>${E(g)}</label>`).join('')}</div></div></div>`}
  function bindRoleScope(){const r=document.querySelector('#v70Role');if(!r)return;const f=()=>{const x=N(r.value);document.querySelector('#v70SupScope').style.display=x==='SUPERVISORA'?'block':'none';document.querySelector('#v70GalScope').style.display=['ADMIN','GERENTE_GALERA'].includes(x)?'block':'none'};r.onchange=f;f()}
  function projectsHtml(u){return (AD.proyectos||[]).map((p,index)=>{const mods=(AD.modulos||[]).filter(m=>m.proyecto_codigo===p.codigo);if(!mods.length)return '';return `<details class="v70-project-block v119-perm-project" ${index===0?'open':''}><summary class="v70-project-title"><span><b>${E(p.nombre)}</b><small>${E(p.descripcion||'Permisos del proyecto')}</small></span><i aria-hidden="true">⌄</i></summary><div class="v119-perm-content"><div class="v70-perm-head"><div>Módulo</div><div>Ver</div><div>Crear</div><div>Editar</div><div>Eliminar</div></div>${mods.map(m=>{const ok=allowedTarget(u.rol,m.codigo);return `<div class="v70-perm-row ${ok?'':'disabled'}"><div class="v70-perm-name"><b>${E(m.nombre)}</b><small>${ok?E(m.grupo||''):'No disponible para este rol'}</small></div>${FIELDS.map(f=>`<div>${permSelect(u.id,u.rol,m.codigo,f,!ok)}</div>`).join('')}</div>`}).join('')}</div></details>`}).join('')}
  function findUser(id){return AD?.users?.find(x=>String(x.id)===String(id))}
  function renderUsersList(){const q=N(document.querySelector('#v70UserQ')?.value||''),box=document.querySelector('#v70UserList');if(!box)return;const a=(AD.users||[]).filter(u=>!q||N([u.nombre,u.usuario,u.email,u.rol].join(' ')).includes(q));box.innerHTML=a.map(u=>`<button class="v70-userrow ${String(u.id)===String(selected)?'active':''}" data-user="${E(u.id)}"><span class="dot ${u.activo?'':'off'}"></span><b>${E(u.nombre||u.usuario)}</b><small>${E(u.usuario||'')} · ${E(u.rol||'')}</small></button>`).join('')||'<div class="v70-empty">Sin resultados.</div>';box.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{selected=b.dataset.user;renderUsersList();renderUserDetail()})}
  function renderUserDetail(){const u=findUser(selected),box=document.querySelector('#v70AdminDetail');if(!box)return;if(!u){box.innerHTML='<div class="v70-empty">Selecciona un usuario.</div>';return}box.innerHTML=`<div class="v70-panel"><div class="v70-panel-head"><h3>${E(u.nombre||u.usuario)}</h3><span class="v70-note">${u.activo?'Activo':'Inactivo'} · ${E(u.rol)}</span></div><div class="v70-panel-body"><div class="v70-form-grid"><div class="v70-field"><label>Nombre</label><input id="v70Name" value="${E(u.nombre||'')}"></div><div class="v70-field"><label>Usuario</label><input value="${E(u.usuario||'')}" readonly></div><div class="v70-field"><label>Correo</label><input id="v70Email" value="${E(u.email||'')}"></div><div class="v70-field"><label>Rol</label><select id="v70Role">${options(ROLES,u.rol)}</select></div></div><div class="v70-checks" style="margin-top:10px"><label class="v70-check"><input id="v70Active" type="checkbox" ${u.activo?'checked':''}> Usuario activo</label></div>${scopeHtml(u)}<div class="v70-actions-row"><button id="v70SaveUser">Guardar perfil</button><button id="v70DeleteUser" class="v70-danger" ${String(u.id)===String(state.profile?.id)?'disabled':''}>Eliminar</button></div><div class="v70-section"><h4>Contraseña</h4><div class="v70-form-grid"><div class="v70-field"><label>Nueva contraseña</label><input id="v70Pwd" type="password" minlength="6" placeholder="Mínimo 6 caracteres"></div><div class="v70-field"><label>Primer ingreso</label><select id="v70Must"><option value="true">Obligar a cambiar</option><option value="false">No obligar</option></select></div></div><div class="v70-actions-row"><button id="v70SetPwd" class="v70-soft">Actualizar contraseña</button></div></div><div class="v70-section"><h4>Permisos por proyecto y módulo</h4><p class="v70-note">Heredado usa el permiso del rol. Sí/No crea una excepción únicamente para este usuario.</p>${projectsHtml(u)}<div class="v70-actions-row"><button id="v70SavePerm">Guardar permisos</button></div></div></div></div>`;bindRoleScope();document.querySelector('#v70SaveUser').onclick=()=>saveUser(u);document.querySelector('#v70SetPwd').onclick=()=>setPwd(u);document.querySelector('#v70SavePerm').onclick=()=>savePerm(u);document.querySelector('#v70DeleteUser').onclick=()=>deleteUser(u)}
  async function saveUser(u){const rol=N(document.querySelector('#v70Role').value),gals=[...document.querySelectorAll('[data-gal]:checked')].map(x=>x.dataset.gal),sup=document.querySelector('#v70SupId')?.value||'';try{await adminApi({action:'update',id:u.id,nombre:document.querySelector('#v70Name').value,email:document.querySelector('#v70Email').value,rol,activo:document.querySelector('#v70Active').checked,supervisora_ids:rol==='SUPERVISORA'&&sup?[sup]:[],galeras_scope:['ADMIN','GERENTE_GALERA'].includes(rol)?gals:[]});await adminLoad();toast('Perfil actualizado');renderUsersList();renderUserDetail()}catch(e){toast(e.message||e)}}
  async function setPwd(u){const p=document.querySelector('#v70Pwd').value;if(p.length<6){toast('Contraseña mínima: 6 caracteres');return}try{await adminApi({action:'set_password',id:u.id,password:p,must_change_password:document.querySelector('#v70Must').value==='true'});document.querySelector('#v70Pwd').value='';toast('Contraseña actualizada')}catch(e){toast(e.message||e)}}
  async function savePerm(u){const map=new Map();document.querySelectorAll('[data-perm-mod]').forEach(s=>{const mod=s.dataset.permMod,f=s.dataset.permField,val=s.value;if(!map.has(mod))map.set(mod,{modulo_codigo:mod,puede_ver:null,puede_crear:null,puede_editar:null,puede_eliminar:null});map.get(mod)[f]=val===''?null:val==='true'});const rows=[...map.values()].filter(x=>FIELDS.some(f=>x[f]!==null));try{await adminApi({action:'permissions',id:u.id,permisos:rows});await adminLoad();toast('Permisos actualizados');renderUserDetail()}catch(e){toast(e.message||e)}}
  async function deleteUser(u){if(!confirm(`Eliminar el acceso de ${u.nombre||u.usuario}?`))return;try{await adminApi({action:'delete',id:u.id});selected=null;await adminLoad();toast('Usuario eliminado');renderAdmin()}catch(e){toast(e.message||e)}}
  function createScope(){return `<div id="v70CreateSup" class="v70-scope-box" style="display:none"><div class="v70-field"><label>Supervisora vinculada</label><select id="v70NewSup"><option value="">Seleccionar...</option>${(AD.supervisoras||[]).map(s=>`<option value="${E(s.id)}">${E(s.nombre)} · ${E(s.galera)}</option>`).join('')}</select></div></div><div id="v70CreateGal" class="v70-scope-box" style="display:none"><div class="v70-field"><label>Galeras</label><div class="v70-checks">${(AD.galeras||[]).map(g=>`<label class="v70-check"><input data-new-gal="${E(g)}" type="checkbox">${E(g)}</label>`).join('')}</div></div></div>`}
  function renderCreate(){const box=document.querySelector('#v70AdminDetail');box.innerHTML=`<div class="v70-panel"><div class="v70-panel-head"><h3>Nuevo usuario</h3><span class="v70-note">El usuario se crea en Auth + perfil RYM.</span></div><div class="v70-panel-body"><div class="v70-form-grid"><div class="v70-field"><label>Nombre</label><input id="v70NewName"></div><div class="v70-field"><label>Correo</label><input id="v70NewEmail" type="email"></div><div class="v70-field"><label>Contraseña inicial</label><input id="v70NewPwd" type="password" minlength="6"></div><div class="v70-field"><label>Rol</label><select id="v70NewRole">${options(ROLES,'SUPERVISORA')}</select></div></div>${createScope()}<div class="v70-checks" style="margin-top:10px"><label class="v70-check"><input id="v70NewMust" type="checkbox" checked> Obligar cambio de contraseña</label></div><div class="v70-actions-row"><button id="v70CreateGo">Crear usuario</button><button id="v70CreateCancel" class="v70-soft">Cancelar</button></div></div></div>`;const r=document.querySelector('#v70NewRole'),toggle=()=>{const x=N(r.value);document.querySelector('#v70CreateSup').style.display=x==='SUPERVISORA'?'block':'none';document.querySelector('#v70CreateGal').style.display=['ADMIN','GERENTE_GALERA'].includes(x)?'block':'none'};r.onchange=toggle;toggle();document.querySelector('#v70CreateCancel').onclick=()=>renderUserDetail();document.querySelector('#v70CreateGo').onclick=async()=>{const rol=N(r.value),sup=document.querySelector('#v70NewSup')?.value||'',gals=[...document.querySelectorAll('[data-new-gal]:checked')].map(x=>x.dataset.newGal);try{const d=await adminApi({action:'create',nombre:document.querySelector('#v70NewName').value,email:document.querySelector('#v70NewEmail').value,password:document.querySelector('#v70NewPwd').value,rol,supervisora_ids:rol==='SUPERVISORA'&&sup?[sup]:[],galeras_scope:['ADMIN','GERENTE_GALERA'].includes(rol)?gals:[],must_change_password:document.querySelector('#v70NewMust').checked});selected=d.id;await adminLoad();toast('Usuario creado');renderAdmin()}catch(e){toast(e.message||e)}}}
  function renderAdmin(){const el=app;document.body.classList.remove('v70-portal','v70-control','v66-revisados','v60-revisados');document.body.classList.add('v70-admin');const active=(AD.users||[]).filter(x=>x.activo).length;el.innerHTML=`<div class="v70-admin-app"><aside class="v70-admin-side"><div class="v70-admin-logo"><img src="https://drive.google.com/thumbnail?id=1f65vwdwsAraUrK2h7cb5l_eVOQKuHsL8&sz=w1000" alt="RYM"><div><h2>Administración RYM</h2><p>Usuarios y permisos</p></div></div><button class="active">Usuarios</button><div class="v70-admin-foot"><button id="v70Back">← Volver al Portal</button></div></aside><main class="v70-admin-main"><header class="v70-admin-top"><div><h1>Usuarios y permisos</h1><p>Administración separada de Panapass, Control de Auto y Revisados.</p></div><span class="badge">${active} activos · ADMIN_TOTAL</span></header><div class="v70-admin-grid"><section class="v70-panel"><div class="v70-panel-head"><h3>Usuarios</h3><button id="v70New" class="v70-soft">+ Nuevo</button></div><div class="v70-panel-body"><input id="v70UserQ" class="v70-search" placeholder="Buscar nombre, usuario o rol"><div id="v70UserList" class="v70-userlist"></div></div></section><section id="v70AdminDetail"></section></div></main></div>`;document.querySelector('#v70Back').onclick=()=>v36PortalHome();document.querySelector('#v70New').onclick=renderCreate;document.querySelector('#v70UserQ').oninput=renderUsersList;if(!selected&&AD.users?.length)selected=AD.users[0].id;renderUsersList();renderUserDetail()}
  async function openUsers(){if(usersRole()!=='ADMIN_TOTAL'||!usersHasModule('admin.usuarios'))return;document.body.classList.remove('v70-portal','v70-control');document.body.classList.add('v70-admin');app.innerHTML='<div style="padding:30px;font-family:Segoe UI,Arial">Cargando Administración RYM...</div>';try{await adminLoad();renderAdmin()}catch(e){app.innerHTML=`<div class="alert">${E(e.message||e)}</div><button onclick="v36PortalHome()">Volver al Portal</button>`}};
  window.v70OpenUsers=openUsers;
  window.RYM_USERS_APP=Object.freeze({open:openUsers});
})(window,document);
