/* Portal RYM V172 clean - portal home permission decorations */
(function(w){
 'use strict';
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const N=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
 const role=()=>N(state?.profile?.rol||'');
 const modules=()=>[...new Set([...(state?.allModules||[]),...(state?.modules||[])].map(String))];
 const has=m=>modules().includes(m);
 const canGps=()=>{const m=modules(),known=m.some(x=>x==='portal.gps'||x.startsWith('gps.'));if(known)return has('portal.gps')||has('gps.dashboard');return ['ADMIN_TOTAL','ADMIN','GERENTE_GALERA','SUPERVISORA','SISTEMA'].includes(role())};
 /* ---------------- Home: GPS/Usuarios por permiso + prioridades clickeables ---------------- */
 async function decorateHome(){if(!document.body.classList.contains('v99-home'))return;const nav=document.querySelector('.v101-nav'),grid=document.querySelector('.v99-grid');if(canGps()){let b=document.querySelector('#v113NavGps');if(!b&&nav){b=document.createElement('button');b.id='v113NavGps';nav.appendChild(b)}if(b){b.innerHTML='⌖ &nbsp; GPS';b.onclick=()=>w.RYM_ROUTER?.open('gps')}let c=document.querySelector('.v99-module.gps');if(!c&&grid){c=document.createElement('article');c.className='v99-module gps';grid.appendChild(c)}if(c){c.innerHTML='<div class="v99-module-head"><div class="v99-modicon">⌖</div><span class="v99-badge">TU ALCANCE</span></div><h4>GPS</h4><p>GPS1/GPS2, prioridades, ranking y ubicación según tu perfil.</p><div class="v99-mini-kpis"><div class="v99-mini"><span>Críticas</span><b>—</b></div><div class="v99-mini"><span>Alertas</span><b>—</b></div><div class="v99-mini"><span>Sin GPS</span><b>—</b></div></div><button>Monitorear GPS</button>';c.querySelector('button').onclick=()=>w.RYM_ROUTER?.open('gps');try{const r=await req('/functions/v1/gps-rym-admin',{method:'POST',body:JSON.stringify({q:'',galera:'TODAS',estado:'TODOS',nivel:'TODOS',onlyProblems:false})}),k=r.data?.kpis||{};c.querySelector('.v99-mini-kpis').innerHTML='<div class="v99-mini"><span>Críticas</span><b>'+Number(k.criticos||0)+'</b></div><div class="v99-mini"><span>Alertas</span><b>'+Number(k.alertas||0)+'</b></div><div class="v99-mini"><span>Sin GPS</span><b>'+Number(k.sin_gps||0)+'</b></div>'}catch(_){}}}else{document.querySelector('#v113NavGps')?.remove();document.querySelector('.v99-module.gps')?.remove()}const mobile=document.querySelector('#v115MobileNav');if(mobile){if(canGps()&&!mobile.querySelector('[data-a="gps"]')){const x=document.createElement('button');x.dataset.a='gps';x.innerHTML='<i>⌖</i><span>GPS</span>';x.onclick=()=>w.RYM_ROUTER?.open('gps');mobile.appendChild(x)}if(role()==='ADMIN_TOTAL'&&has('admin.usuarios')&&!mobile.querySelector('[data-a="users"]')){const x=document.createElement('button');x.dataset.a='users';x.innerHTML='<i>U</i><span>Usuarios</span>';x.onclick=()=>w.RYM_ROUTER?.open('usuarios');mobile.appendChild(x)}}document.querySelectorAll('.v99-alert').forEach(x=>x.classList.add('v154-clickable'))}
 if(!window.__v154PriorityBound){window.__v154PriorityBound=true;document.addEventListener('click',async e=>{const a=e.target.closest('body.v99-home .v99-alert');if(!a)return;const t=N(a.textContent);if(t.includes('REVISADO')&&t.includes('CRIT')){await w.RYM_ROUTER?.open('revisados',{tab:'operations'});setTimeout(()=>{[...document.querySelectorAll('.v66-nav button')].find(x=>/Operaciones/i.test(x.textContent||''))?.click();setTimeout(()=>{const p=document.querySelector('#v66OP');if(p){p.value='CRITICA';p.dispatchEvent(new Event('change',{bubbles:true}))}},120)},80)}else if(t.includes('BAJA')&&t.includes('PROCESAD')){await w.RYM_ROUTER?.open('panapass',{tab:'bajas_panapass'});setTimeout(()=>document.querySelector('[data-v99bt="processed"]')?.click(),80)}else if(t.includes('SIN PANAPASS')||t.includes('NO ENCONTRADO EN ENA')){await w.RYM_ROUTER?.open('panapass',{tab:'bajas_panapass'});setTimeout(()=>document.querySelector('[data-v99bt="alerts"]')?.click(),80)}},true)}
 setTimeout(()=>{if(document.body.classList.contains('v99-home'))decorateHome();if(document.body.classList.contains('v70-control'))enhanceControl()},80);

 w.RYM_HOME_V154=Object.freeze({decorate:decorateHome});
})(window);
