/* Portal RYM V172 clean - Panapass pagosConsultaHoy */
async function pagosConsultaHoy(v){
  const hoy=state.today||new Date().toISOString().slice(0,10);
  v.innerHTML=`<div class="source-card"><span class="entity-chip">PAGOS REGISTRADOS</span><div class="source-text"><strong>Resultado real de cobranza de tus unidades</strong><p>Por defecto ves lo pagado hoy. Puedes consultar una fecha anterior, pero no editar: la hoja online de trabajo es exclusiva de administración/personal autorizado.</p></div></div><div class="section-tools"><div class="field"><label>Fecha</label><input id="supPayFecha" type="date" value="${hoy}" max="${hoy}"></div><div class="field"><label>Buscar</label><input id="supPayQ" placeholder="Unidad, operador o empresa"></div><button id="supPayLoad">Consultar</button></div><div id="supPayOut"><div class="card">Cargando pagos...</div></div>`;
  let rows=[];
  function paint(){const q=document.querySelector('#supPayQ').value.trim().toLowerCase();let d=rows;if(q)d=d.filter(x=>[x.unidad,x.operador,x.n_op,x.empresa,x.cobrador].join(' ').toLowerCase().includes(q));const total=d.reduce((a,x)=>a+Number(x.boleta||x.a_pagar||0),0);document.querySelector('#supPayOut').innerHTML=`<div class="kpis"><div class="kpi"><span>Pagos</span><strong>${d.length}</strong></div><div class="kpi"><span>Total pagado</span><strong style="color:var(--green)">${money(total)}</strong></div></div>${tableHtml(d,['fecha','unidad','empresa','a_pagar','boleta','n_op','operador','tipo'],'pretty','mobile-cards')}`}
  async function load(){const o=document.querySelector('#supPayOut'),f=document.querySelector('#supPayFecha').value||hoy;o.innerHTML='<div class="card">Consultando pagos...</div>';try{rows=await rpc('panapass_pagos_fecha',{p_fecha:f});paint()}catch(x){o.innerHTML=`<div class="alert">${esc(x.message)}</div>`}}
  document.querySelector('#supPayLoad').onclick=load;document.querySelector('#supPayFecha').onchange=load;document.querySelector('#supPayQ').oninput=paint;await load();
}
